{
  "compatibilityLevel": 1601,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Servidor\",\"Banco\",\"fMonitorPedido\",\"Calendario\",\"dVendedores\",\"dClientes\",\"dUnidade\",\"fConsolidado_Faturamento\",\"dProduto\",\"Meta\",\"dCanal_de vendas\",\"Medidas_Fat\",\"Medidas_Cart\",\"Medidas_Posit\",\"Medidas_YTG\",\"Medidas_Ton\",\"Servidor (2)\",\"Banco (2)\",\"dEstabelecimento\",\"RLS\",\"Estrategico Coord_Vend\",\"Data Atualização\",\"dFaixa\",\"Faixa\",\"Faixa Volume\",\"Medidas CurvasABC\",\"AuxiliarABC\",\"Estrategico_Gerencia\",\"Medidas_Lanç\",\"dVend_Auxi\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.1452.0 (24.11)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DaxQueryView_Desktop\",\"CalcGroup\",\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "fastCombine": true,
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "expressions": [
      {
        "name": "Servidor",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "expression": "\"192.168.24.60\\SQL2022\" meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "ec6c4de1-eeb1-4bcb-a505-b63546fd5c66"
      },
      {
        "name": "Banco",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"DW\" meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "7016c6f0-b91c-46d3-82b1-9c661ff54466"
      },
      {
        "name": "Servidor (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"192.168.24.60\\SQL2022\" meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "9c379059-0856-4368-a74c-ea58195d4759"
      },
      {
        "name": "Banco (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"DW\" meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "5d9e6dde-844c-48ae-9f80-f44b6da05428"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Servidor"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Bases Manuais"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Medidas"
      }
    ],
    "relationships": [
      {
        "name": "37f3864a-43d8-d5c1-d65a-57785cf42eb0",
        "fromColumn": "DataImplant",
        "fromTable": "fMonitorPedido",
        "toColumn": "Data",
        "toTable": "Calendario"
      },
      {
        "name": "b368d0f7-b1f5-3fd0-a851-e04e6a318ee5",
        "fromColumn": "DataFaturamento",
        "fromTable": "fConsolidado_Faturamento",
        "toColumn": "Data",
        "toTable": "Calendario"
      },
      {
        "name": "ba8091c2-cc0d-3a72-3330-82e44bb626f5",
        "fromColumn": "EmpresaId",
        "fromTable": "Meta",
        "toColumn": "subEmpresaid",
        "toTable": "dUnidade"
      },
      {
        "name": "2cdb3995-f630-9a8a-96fd-4ecbebf81d6d",
        "fromColumn": "Data",
        "fromTable": "Meta",
        "toColumn": "Data",
        "toTable": "Calendario"
      },
      {
        "name": "87a0177c-d7ed-3c9a-eb14-1935ed2023cc",
        "fromColumn": "EmpresaId",
        "fromTable": "fMonitorPedido",
        "toColumn": "subEmpresaid",
        "toTable": "dUnidade"
      },
      {
        "name": "AutoDetected_4c054e66-e83f-478e-bbf3-38004c7cd269",
        "fromColumn": "Vendedorid",
        "fromTable": "Meta",
        "toColumn": "VendedorId",
        "toTable": "dVendedores"
      },
      {
        "name": "9710ee0d-a635-46ae-92e7-5a1820851d4a",
        "fromColumn": "ProdutoId",
        "fromTable": "Meta",
        "toColumn": "ProdutoId",
        "toTable": "dProduto"
      },
      {
        "name": "74c97757-7673-8b2b-d954-8aedc0d4c93e",
        "fromColumn": "produtoID",
        "fromTable": "fConsolidado_Faturamento",
        "toColumn": "ProdutoId",
        "toTable": "dProduto"
      },
      {
        "name": "c33b1adf-b202-3c29-c1ea-254983175484",
        "fromColumn": "ProdutoId",
        "fromTable": "fMonitorPedido",
        "toColumn": "ProdutoId",
        "toTable": "dProduto"
      },
      {
        "name": "AutoDetected_55da570f-7c7a-4ab3-9838-7041b9611ce1",
        "fromColumn": "Estabelecimentoid",
        "fromTable": "fMonitorPedido",
        "toColumn": "Estabelecimentoid",
        "toTable": "dEstabelecimento"
      },
      {
        "name": "AutoDetected_de7f99bd-9789-497b-b7d8-66c03dbd75a0",
        "fromColumn": "Estabelecimentoid",
        "fromTable": "fConsolidado_Faturamento",
        "toColumn": "Estabelecimentoid",
        "toTable": "dEstabelecimento"
      },
      {
        "name": "f3607e39-e78c-7016-8a4a-8fc982d891a8",
        "fromColumn": "emitenteID",
        "fromTable": "fConsolidado_Faturamento",
        "toColumn": "Emitenteid",
        "toTable": "dClientes"
      },
      {
        "name": "AutoDetected_ebc870f9-81b8-4aa8-8a76-aa2df2698eb5",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Vendedorid",
        "fromTable": "RLS",
        "securityFilteringBehavior": "bothDirections",
        "toColumn": "VendedorId",
        "toTable": "dVendedores"
      },
      {
        "name": "f0ab2aef-a647-9d95-dc47-1e55a6fabfb4",
        "fromColumn": "PerfilEstrategico",
        "fromTable": "Meta",
        "toColumn": "chave",
        "toTable": "Estrategico Coord_Vend"
      },
      {
        "name": "1159c5bf-8b60-3f65-041f-1496447686dc",
        "fromColumn": "ProdutoPerfilEstrategico",
        "fromTable": "fConsolidado_Faturamento",
        "toColumn": "chave",
        "toTable": "Estrategico Coord_Vend"
      },
      {
        "name": "3cf9fa97-277d-06d7-71ad-04e1e6146548",
        "fromColumn": "PerfilEstrategico",
        "fromTable": "fMonitorPedido",
        "toColumn": "chave",
        "toTable": "Estrategico Coord_Vend"
      },
      {
        "name": "AutoDetected_e41c16fd-c31b-4921-8a9e-0d79ca22bf57",
        "fromColumn": "VendedorId",
        "fromTable": "Faixa",
        "toColumn": "VendedorId",
        "toTable": "dVendedores"
      },
      {
        "name": "AutoDetected_7b20acac-d4e2-469d-8506-d599d134362a",
        "fromColumn": "clipocliente",
        "fromTable": "fMonitorPedido",
        "toColumn": "CLIPO CLIENTE",
        "toTable": "dCanal_de vendas"
      },
      {
        "name": "03a22a0f-58e3-a9d8-abf4-9eec3d92c905",
        "fromColumn": "PerfilEstrategico",
        "fromTable": "fMonitorPedido",
        "toColumn": "Chave",
        "toTable": "Estrategico_Gerencia"
      },
      {
        "name": "329c7b79-15a3-612d-4b8a-dcc397be8f8c",
        "fromColumn": "PerfilEstrategico",
        "fromTable": "Meta",
        "toColumn": "Chave",
        "toTable": "Estrategico_Gerencia"
      },
      {
        "name": "AutoDetected_4b32ea9c-91d7-4e4d-9e88-e65b9a5b3a65",
        "fromColumn": "Emitenteid",
        "fromTable": "fMonitorPedido",
        "toColumn": "Emitenteid",
        "toTable": "dClientes"
      },
      {
        "name": "8dc4610c-dcd5-04bb-e258-4152400b5c07",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Fabrica",
        "fromTable": "dProduto",
        "securityFilteringBehavior": "bothDirections",
        "toCardinality": "many",
        "toColumn": "Denominacao",
        "toTable": "dUnidade"
      },
      {
        "name": "676a3a7d-6c44-356e-f66b-f9f4bf6ac0b3",
        "fromColumn": "ProdutoPerfilEstrategico",
        "fromTable": "fConsolidado_Faturamento",
        "toColumn": "Chave",
        "toTable": "Estrategico_Gerencia"
      },
      {
        "name": "508232cb-97dc-336e-2f70-9f2c1c374d96",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "dVendedores.VendedorId",
        "fromTable": "Estrategico_Gerencia",
        "securityFilteringBehavior": "bothDirections",
        "toCardinality": "many",
        "toColumn": "VendedorId",
        "toTable": "dVend_Auxi"
      },
      {
        "name": "5fb39b2b-8e84-c5a4-9a47-27345a8ce672",
        "fromColumn": "Vendedorid",
        "fromTable": "Meta",
        "toColumn": "VendedorId",
        "toTable": "dVend_Auxi"
      },
      {
        "name": "e454d259-51a0-0a6d-6597-159bed69a9a2",
        "fromColumn": "vendedorID",
        "fromTable": "fConsolidado_Faturamento",
        "toColumn": "VendedorId",
        "toTable": "dVend_Auxi"
      },
      {
        "name": "a83ae752-ca5e-83c5-9cbf-d8dc532cfd3c",
        "fromColumn": "Vendedorid",
        "fromTable": "fMonitorPedido",
        "toColumn": "VendedorId",
        "toTable": "dVend_Auxi"
      },
      {
        "name": "ab38a7c9-7590-0e5c-a118-d2bbc31b626d",
        "fromColumn": "VendedorId",
        "fromTable": "Faixa",
        "toColumn": "VendedorId",
        "toTable": "dVend_Auxi"
      },
      {
        "name": "fc46de2e-89ee-3d80-326b-c6e48a2c497b",
        "fromColumn": "ClipoCliente",
        "fromTable": "fConsolidado_Faturamento",
        "toColumn": "CLIPO CLIENTE",
        "toTable": "dCanal_de vendas"
      },
      {
        "name": "3a23eea8-f49c-5e98-1ef1-8d6a37e17afc",
        "fromColumn": "Fabrica",
        "fromTable": "fConsolidado_Faturamento",
        "toColumn": "Denominacao",
        "toTable": "dUnidade"
      },
      {
        "name": "9f768945-c1e0-7110-a930-552fd7650640",
        "fromColumn": "Vend Aux 3",
        "fromTable": "fConsolidado_Faturamento",
        "toColumn": "VendedorId",
        "toTable": "dVendedores"
      },
      {
        "name": "417feb55-aeea-9acd-310a-3eb802e0825c",
        "fromColumn": "Vend Aux 2",
        "fromTable": "fMonitorPedido",
        "toColumn": "VendedorId",
        "toTable": "dVendedores"
      }
    ],
    "roles": [
      {
        "name": "Rls_Acesso",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "4645fbb9709047ecb03df0e6bdcbff41"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "RLS",
            "filterExpression": "RLS[email]==USERPRINCIPALNAME()"
          }
        ]
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "fMonitorPedido",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "ProdutoId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "42e4c969-46dd-49ef-9b61-674096398f10",
            "sourceColumn": "ProdutoId",
            "summarizeBy": "none"
          },
          {
            "name": "EmpresaId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e62db5e7-272f-4528-8c55-3c1a44e403f7",
            "sourceColumn": "EmpresaId",
            "summarizeBy": "none"
          },
          {
            "name": "NumeroPedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "lineageTag": "920f7a14-03cc-48da-9e9b-82409fcfce2e",
            "sourceColumn": "NumeroPedido",
            "summarizeBy": "none"
          },
          {
            "name": "DataImplant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yy",
            "lineageTag": "cf0e13ab-94ec-4030-b86e-f7d5f51414a7",
            "sourceColumn": "DataImplant",
            "summarizeBy": "none"
          },
          {
            "name": "DataCancelamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "5b16fc4f-182c-403b-8cf1-6205c4809777",
            "sourceColumn": "DataCancelamento",
            "summarizeBy": "none"
          },
          {
            "name": "DataProvPreco",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yy",
            "lineageTag": "bae04eb0-50b3-468f-94d8-24274c21048b",
            "sourceColumn": "DataProvPreco",
            "summarizeBy": "none"
          },
          {
            "name": "QtdPedida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "2b7a534b-bbe0-4b0a-8f33-156a6bf35e74",
            "sourceColumn": "QtdPedida",
            "summarizeBy": "sum"
          },
          {
            "name": "QtdAtendida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "41466992-f5e2-48cf-b396-3575d3a67c1b",
            "sourceColumn": "QtdAtendida",
            "summarizeBy": "sum"
          },
          {
            "name": "QtdAberta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "37f8eb6c-a2c2-4cc7-96b7-5d9cf2b394de",
            "sourceColumn": "QtdAberta",
            "summarizeBy": "sum"
          },
          {
            "name": "QtdCancelada",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "e1755d79-d271-44d8-9b26-c7dc96f8fb19",
            "sourceColumn": "QtdCancelada",
            "summarizeBy": "sum"
          },
          {
            "name": "PrecoTabela",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "4740a588-0ffb-48b5-9215-138bd2b2e495",
            "sourceColumn": "PrecoTabela",
            "summarizeBy": "sum"
          },
          {
            "name": "Vl Líquido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "cca77ac8-7cc8-4b76-961b-20cc5a0d520c",
            "sourceColumn": "Vl Líquido",
            "summarizeBy": "sum"
          },
          {
            "name": "Vl Líq Aberto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "66def98b-7abe-4e44-ae0c-240268d168df",
            "sourceColumn": "Vl Líq Aberto",
            "summarizeBy": "sum"
          },
          {
            "name": "vlpreuni",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "676681e8-4d1a-4ee9-9ef8-9051328e2cec",
            "sourceColumn": "vlpreuni",
            "summarizeBy": "sum"
          },
          {
            "name": "SitPreco",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "9043aed1-3bd3-401e-b34a-086b2f9ed460",
            "sourceColumn": "SitPreco",
            "summarizeBy": "none"
          },
          {
            "name": "SitCredito",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "d84fce5e-0306-48a6-9304-52d35fee0d62",
            "sourceColumn": "SitCredito",
            "summarizeBy": "none"
          },
          {
            "name": "SitPedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "034756b8-1c44-4b74-a932-b07809d06db0",
            "sourceColumn": "SitPedido",
            "summarizeBy": "none"
          },
          {
            "name": "SitItem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d214875-d71f-446e-add6-0873c9f5bc7c",
            "sourceColumn": "SitItem",
            "summarizeBy": "none"
          },
          {
            "name": "SitAlocacao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "f7d6ca49-e09f-4130-8625-2d29958590dc",
            "sourceColumn": "SitAlocacao",
            "summarizeBy": "none"
          },
          {
            "name": "SitCarteira",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "92364b6d-0b9e-466c-98ab-7eb2f430bd04",
            "sourceColumn": "SitCarteira",
            "summarizeBy": "none"
          },
          {
            "name": "PesoLiquidoTotal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "511a7664-61f2-429e-825d-c373107edc57",
            "sourceColumn": "PesoLiquidoTotal",
            "summarizeBy": "sum"
          },
          {
            "name": "PerfilLog",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "0fbbe585-6a6f-4f8b-a597-8e71d8217e77",
            "sourceColumn": "PerfilLog",
            "summarizeBy": "none"
          },
          {
            "name": "Vendedorid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3f2db037-54c4-4956-8dba-abf45a1b28d2",
            "sourceColumn": "Vendedorid",
            "summarizeBy": "none"
          },
          {
            "name": "Sit Carteira 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF(fMonitorPedido[SitCarteira] = \"BAIXO PESO\", \"NÃO FECHA ROTA\", IF(fMonitorPedido[SitCarteira] = BLANK(), \"SEM CLASSIFICAÇÃO\", fMonitorPedido[SitCarteira]))",
            "isDataTypeInferred": true,
            "lineageTag": "a11987fc-7f1e-4fcd-a7e5-a7879aa47a30",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Aging Cancelamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": "IF(fMonitorPedido[DataCancelamento] = BLANK(), 0, fMonitorPedido[DataCancelamento]-fMonitorPedido[DataImplant])",
            "formatString": "0",
            "lineageTag": "4c2fb869-097f-4177-b59e-06a5e89be9eb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Valor Cancelado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "double",
            "expression": "fMonitorPedido[QtdCancelada]*fMonitorPedido[PrecoTabela]",
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "isDataTypeInferred": true,
            "lineageTag": "d4622d9e-251b-485e-b0bd-3a7a46ad1e7e",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Estabelecimentoid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f181e4c6-3280-4159-bde0-d0be2e37a4f8",
            "sourceColumn": "Estabelecimentoid",
            "summarizeBy": "none"
          },
          {
            "name": "PesoLiqAberto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4c889338-ea23-4a12-b469-813520a9aa35",
            "sourceColumn": "PesoLiqAberto",
            "summarizeBy": "sum"
          },
          {
            "name": "MotivoCancelamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9d1012c5-4446-458a-916e-2413482dfc98",
            "sourceColumn": "MotivoCancelamento",
            "summarizeBy": "none"
          },
          {
            "name": "usuariocancelamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f7a60f27-586d-4ea3-9f64-e379672619d1",
            "sourceColumn": "usuariocancelamento",
            "summarizeBy": "none"
          },
          {
            "name": "Nome do Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "768c54a5-e2d0-4122-9a33-b7607543a8df",
            "sourceColumn": "Nome do Mês",
            "summarizeBy": "none"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "71f38d1e-4140-4bcc-995e-df4680e52842",
            "sourceColumn": "Mês",
            "summarizeBy": "sum"
          },
          {
            "name": "PerfilEstrategico",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e521231-42b0-4443-bb7a-6247c72bf686",
            "sourceColumn": "PerfilEstrategico",
            "summarizeBy": "none"
          },
          {
            "name": "Usuario Cancelamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15defc78-8179-498a-bb46-c5be7ee6ff1b",
            "sourceColumn": "Usuario Cancelamento",
            "summarizeBy": "none"
          },
          {
            "name": "CodCancelamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "30b57de4-73e7-490f-8d70-663cba5bbf9f",
            "sourceColumn": "CodCancelamento",
            "summarizeBy": "sum"
          },
          {
            "name": "DescricaoCancelamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4fb205e9-b275-4be4-9395-93b3d8b78904",
            "sourceColumn": "DescricaoCancelamento",
            "summarizeBy": "none"
          },
          {
            "name": "Peso cancelado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "dataType": "double",
            "expression": "fMonitorPedido[QtdCancelada]*RELATED(dProduto[PesoKG])/1000",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "2329a091-7144-48ab-bcf3-3344ec3c0153",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "clipocliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ddfd98af-bd15-4c9c-8048-886d0f2f8457",
            "sourceColumn": "clipocliente",
            "summarizeBy": "none"
          },
          {
            "name": "MotivoCancelamentoId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "638f011e-c54d-4565-87b3-58b2c47c5f1a",
            "sourceColumn": "MotivoCancelamentoId",
            "summarizeBy": "count"
          },
          {
            "name": "Emitenteid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "99f56efd-7036-468d-baed-3eeb832e8599",
            "sourceColumn": "Emitenteid",
            "summarizeBy": "none"
          },
          {
            "name": "Aging pedidos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "expression": "TODAY()- fMonitorPedido[DataImplant]",
            "formatString": "0",
            "lineageTag": "c14acfad-cf50-4ad2-81f8-92e4772271f6",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Vend Aux 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(), ",
              "    fMonitorPedido[Emitenteid]  = 744148 && fMonitorPedido[EmpresaId] = 6, 1123,",
              "     fMonitorPedido[Emitenteid]  = 744148 && fMonitorPedido[EmpresaId] = 3, 1146,",
              "      fMonitorPedido[Emitenteid]  = 744148 && fMonitorPedido[EmpresaId] = 4, 1146,",
              "      fMonitorPedido[Emitenteid]  = 744148 && fMonitorPedido[EmpresaId] = 5, 1146,",
              "    fMonitorPedido[Vendedorid])"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "a0f64816-eb9e-4d8c-9c0c-4894c8d56792",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "c88f4994-0819-4517-a774-224c4887b115",
        "partitions": [
          {
            "name": "fMonitorPedido",
            "mode": "import",
            "queryGroup": "Servidor",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(Servidor, Banco),",
                "    bi_view_Pedido = Fonte{[Schema=\"bi\",Item=\"view_Pedido\"]}[Data],",
                "    #\"Nome do Mês Inserido\" = Table.AddColumn(bi_view_Pedido, \"Nome do Mês\", each Date.MonthName([DataCancelamento]), type text),",
                "    #\"Mês Inserido\" = Table.AddColumn(#\"Nome do Mês Inserido\", \"Mês\", each Date.Month([DataCancelamento]), Int64.Type),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Mês Inserido\",null,0,Replacer.ReplaceValue,{\"Mês\"}),",
                "    #\"Valor Substituído1\" = Table.ReplaceValue(#\"Valor Substituído\",null,\"0\",Replacer.ReplaceValue,{\"Nome do Mês\"}),",
                "    #\"Colocar Cada Palavra Em Maiúscula\" = Table.TransformColumns(#\"Valor Substituído1\",{{\"MotivoCancelamento\", Text.Proper, type text}}),",
                "    #\"Coluna Condicional Adicionada\" = Table.AddColumn(#\"Colocar Cada Palavra Em Maiúscula\", \"Usuario Cancelamento\", each if [usuariocancelamento] = \"totvs\" then \"TOTVS\" else if [usuariocancelamento] = null then \"SEM CLASSIFICAÇÃO\" else if [usuariocancelamento] = \"\" then \"SEM CLASSIFICAÇÃO\" else if [usuariocancelamento] = \"edna\" then \"COMERCIAL\" else if [usuariocancelamento] = \"ana.bc\" then \"COMERCIAL\" else if [usuariocancelamento] = \"flavio.ba\" then \"COMERCIAL\" else if [usuariocancelamento] = \"leticia.cs\" then \"COMERCIAL\" else if [usuariocancelamento] = \"marcelle.mc\" then \"CONTROLADORIA\" else if [usuariocancelamento] = \"marcos.mc\" then \"FARELO\" else if [usuariocancelamento] = \"TOTVS\" then \"TOTVS\" else if [usuariocancelamento] = \"ADM. VENDAS\" then \"COMERCIAL\" else \"SEM CLASSIFICAÇÃO\"),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Coluna Condicional Adicionada\",{{\"Usuario Cancelamento\", type text}}),",
                "    #\"Texto em Maiúscula\" = Table.TransformColumns(#\"Tipo Alterado\",{{\"DescricaoCancelamento\", Text.Upper, type text}}),",
                "    #\"Valor Substituído2\" = Table.ReplaceValue(#\"Texto em Maiúscula\",null,\"SEM CLASSIFICAÇÃO\",Replacer.ReplaceValue,{\"DescricaoCancelamento\"}),",
                "    #\"Valor Substituído3\" = Table.ReplaceValue(#\"Valor Substituído2\",\"CANCELAMENTO - NÃO UTILIZAR\",\"SEM CLASSIFICAÇÃO\",Replacer.ReplaceText,{\"DescricaoCancelamento\"}),",
                "    #\"Valor Substituído4\" = Table.ReplaceValue(#\"Valor Substituído3\",\"CANCEL. OUTROS MOTIVOS -\",\"\",Replacer.ReplaceText,{\"DescricaoCancelamento\"}),",
                "    #\"Valor Substituído5\" = Table.ReplaceValue(#\"Valor Substituído4\",\"\",\"SEM CLASSIFICAÇÃO\",Replacer.ReplaceValue,{\"DescricaoCancelamento\"}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Valor Substituído5\",{\"DataEmissao\", \"DataEntrega\", \"RedeId\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendario",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "6f7c13ed-05fd-4cd4-8e40-03c136d0a727",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c28062e-9d67-459f-8d64-a3afd0ccfb88",
            "sourceColumn": "Ano",
            "summarizeBy": "none"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "985eeae1-c944-455c-bf24-30877c0baa75",
            "sourceColumn": "Mês",
            "summarizeBy": "sum"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c579f37-26e3-44b7-92eb-015f800b49ea",
            "sourceColumn": "Trimestre",
            "summarizeBy": "none"
          },
          {
            "name": "Semestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "860a8194-1150-4f2d-bc6f-8b32f63f03cb",
            "sourceColumn": "Semestre",
            "summarizeBy": "none"
          },
          {
            "name": "Mês 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ac36eda-e301-475d-ada6-f091d91be8f3",
            "sortByColumn": "Mês",
            "sourceColumn": "Mês 1",
            "summarizeBy": "none"
          },
          {
            "name": "Mês 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "22ce0dba-f158-4e3a-a1a6-1b8197786377",
            "sortByColumn": "Mês",
            "sourceColumn": "Mês 2",
            "summarizeBy": "none"
          },
          {
            "name": "Dia Semana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "5aff8de6-3e93-40ce-a800-c1a1ab164748",
            "sourceColumn": "Dia Semana",
            "summarizeBy": "none"
          },
          {
            "name": "numeroDiaSemana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ab5290d7-9737-438b-97fb-8af6199d5cac",
            "sourceColumn": "numeroDiaSemana",
            "summarizeBy": "sum"
          },
          {
            "name": "Semana Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "d220fb47-fe8a-4f3d-9156-8ac49a65f3c7",
            "sourceColumn": "Semana Mês",
            "summarizeBy": "none"
          },
          {
            "name": "Dia Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d9bab25f-bc7f-49ed-9641-2775f86f0c43",
            "sourceColumn": "Dia Mês",
            "summarizeBy": "sum"
          },
          {
            "name": "PosicaoAtual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "bb842058-4a32-4625-b359-97bf43ec2e2e",
            "sourceColumn": "PosicaoAtual",
            "summarizeBy": "none"
          },
          {
            "name": ".",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "\".\"",
            "isDataTypeInferred": true,
            "lineageTag": "1d23da5d-764d-44bb-b133-587608417f40",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "ab08b540-3eb8-49bf-9249-3a3e324ad1c4",
        "partitions": [
          {
            "name": "Calendario",
            "mode": "import",
            "queryGroup": "Servidor",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(Servidor, Banco),",
                "    bi_view_PeriodoCarteira = Fonte{[Schema=\"bi\",Item=\"view_PeriodoCarteira\"]}[Data],",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(bi_view_PeriodoCarteira,{\"Passado\", \"Semana2\", \"Semana\", \"anomes\", \"Mês 4\", \"Ano/Mês\", \"Mês 5\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dVendedores",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Codigo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4978f7b5-76f8-49ad-b2ef-7fef3d4daade",
            "sourceColumn": "Codigo",
            "summarizeBy": "sum"
          },
          {
            "name": "VendedorId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bae80a6e-b4ee-40be-aa67-116177c1444e",
            "sourceColumn": "VendedorId",
            "summarizeBy": "none"
          },
          {
            "name": "Nome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "7bc0d81a-1292-40e4-a205-47f25b387577",
            "sourceColumn": "Nome",
            "summarizeBy": "none"
          },
          {
            "name": "regional",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "d4163931-230f-4eeb-aa80-62bd542a8fbb",
            "sourceColumn": "regional",
            "summarizeBy": "none"
          },
          {
            "name": "STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "e674b922-3010-4bfc-92a1-34b8def67d43",
            "sourceColumn": "STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "NomeGerente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "67d548ca-c50c-4d8d-844b-e67150dfc69b",
            "sourceColumn": "NomeGerente",
            "summarizeBy": "none"
          },
          {
            "name": "CodigoGerente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6f0d2afb-ef3d-435e-9324-885df99f5044",
            "sourceColumn": "CodigoGerente",
            "summarizeBy": "sum"
          },
          {
            "name": "NomeCoordenador",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "922c6957-b824-48e7-935e-c924cc494616",
            "sourceColumn": "NomeCoordenador",
            "summarizeBy": "none"
          },
          {
            "name": "CodigoCoordenador",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e5d773ea-4253-450d-b81d-51770f3ceef1",
            "sourceColumn": "CodigoCoordenador",
            "summarizeBy": "sum"
          },
          {
            "name": "REG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "IF(",
              "    dVendedores[regional] = \"GERENCIA VAREJO\", \"GER VAR\", IF(dVendedores[regional] = \"GERENCIA MULTICANAL\", \"GER MULTI\", dVendedores[regional]))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "69730be5-1630-4b5b-ab95-eb1c57cafa33",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "perfil",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0eb16f4c-0366-4851-9541-462196ff6904",
            "sourceColumn": "perfil",
            "summarizeBy": "none"
          },
          {
            "name": "Chave2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b8ff792-8094-4df9-8619-5f479e7201dd",
            "sourceColumn": "Chave2",
            "summarizeBy": "none"
          },
          {
            "name": "REGIONAL AUXI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "903344fa-b0e9-42cb-8485-fbeb148e66b7",
            "sourceColumn": "REGIONAL AUXI",
            "summarizeBy": "none"
          },
          {
            "name": "PerfilRmv",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58018bd1-f915-49b7-afb1-861f6ad6a00c",
            "sourceColumn": "PerfilRmv",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f92b7ae7-2752-4e76-8dd2-25f4ee17d7ed",
        "partitions": [
          {
            "name": "dVendedores",
            "mode": "import",
            "queryGroup": "Bases Manuais",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(Servidor, Banco),",
                "    bi_view_PessoaVendedor = Fonte{[Schema=\"bi\",Item=\"view_vendedor\"]}[Data],",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(bi_view_PessoaVendedor,{{\"Codigo\", Int64.Type}, {\"CodigoGerente\", Int64.Type}, {\"CodigoCoordenador\", Int64.Type}}),",
                "    #\"Coluna Mesclada Inserida\" = Table.AddColumn(#\"Tipo Alterado\", \"Chave2\", each Text.Combine({Text.From([VendedorId], \"pt-BR\"), [regional]}, \"|\"), type text),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Coluna Mesclada Inserida\",null,\"OUTROS\",Replacer.ReplaceValue,{\"regional\"}),",
                "    #\"Coluna Condicional Adicionada\" = Table.AddColumn(#\"Valor Substituído\", \"REGIONAL AUXI\", each if [VendedorId] = 911 then \"GERENCIA MULTICANAL\" else if Text.Contains([regional], \"SP\") then \"REGIONAL RJ\" else if [VendedorId] = 1618 then \"EXPORTAÇÃO\" else [regional]),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Coluna Condicional Adicionada\", each true),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Linhas Filtradas\",{{\"REGIONAL AUXI\", type text}}),",
                "    #\"Valor Substituído1\" = Table.ReplaceValue(#\"Tipo Alterado1\",\"0\",\"REPRESENTANTE\",Replacer.ReplaceText,{\"PerfilRmv\"}),",
                "    #\"Valor Substituído2\" = Table.ReplaceValue(#\"Valor Substituído1\",null,\"OUTROS\",Replacer.ReplaceValue,{\"PerfilRmv\"})",
                "in",
                "    #\"Valor Substituído2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dClientes",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Codigo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "c06edb0f-8d29-44c0-9b0b-be6c91ea7516",
            "sourceColumn": "Codigo",
            "summarizeBy": "none"
          },
          {
            "name": "Emitenteid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "90a62f4b-e2a9-412d-b6ca-a071054d83d3",
            "sourceColumn": "Emitenteid",
            "summarizeBy": "none"
          },
          {
            "name": "Origemid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f8679f2-cdce-46ff-aaf5-2b4c54e5138b",
            "sourceColumn": "Origemid",
            "summarizeBy": "none"
          },
          {
            "name": "Bairro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "e95c0ffc-23be-4c3c-aced-95170b1b7a2e",
            "sourceColumn": "Bairro",
            "summarizeBy": "none"
          },
          {
            "name": "Cidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataCategory": "City",
            "dataType": "string",
            "lineageTag": "83517bd8-1f60-4cee-9469-ea5007ecc299",
            "sourceColumn": "Cidade",
            "summarizeBy": "none"
          },
          {
            "name": "UF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataCategory": "StateOrProvince",
            "dataType": "string",
            "lineageTag": "a9f01f83-e156-4cce-ac6a-3057d6952cef",
            "sourceColumn": "UF",
            "summarizeBy": "none"
          },
          {
            "name": "CodigoRota",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdacf263-d464-45a9-b13f-0db606dedd73",
            "sourceColumn": "CodigoRota",
            "summarizeBy": "none"
          },
          {
            "name": "nomeRede",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "6aab78b1-04c5-4aaf-b37d-2c2b4bd5c302",
            "sourceColumn": "nomeRede",
            "summarizeBy": "none"
          },
          {
            "name": "nome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "656ec2da-84dd-47be-b4d3-4fb2f299ac26",
            "sourceColumn": "nome",
            "summarizeBy": "none"
          },
          {
            "name": "REDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(dClientes[nomeRede] = BLANK(), dClientes[nome], dClientes[nomeRede])",
            "isDataTypeInferred": true,
            "lineageTag": "b5277930-a82f-4bb1-9183-64f7e0210551",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CONCAT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "expression": "COMBINEVALUES( \", \", dClientes[REDE], dClientes[Cidade],dClientes[UF])",
            "isDataTypeInferred": true,
            "lineageTag": "1edb2546-6f82-4818-b11e-cbba7cae8cf7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Pais",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "StateOrProvince",
            "dataType": "string",
            "expression": "\"Brasil - \" & dClientes[UF]",
            "isDataTypeInferred": true,
            "lineageTag": "83d5508f-757e-4d1a-a4db-5d8e859fc8fc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Pais2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Country",
            "dataType": "string",
            "expression": "\"Brasil\"",
            "isDataTypeInferred": true,
            "lineageTag": "093a5696-ae00-45ac-8b74-a47a58b00771",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "VendedorId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cd770bb5-be95-4e36-812f-9f655f24481c",
            "sourceColumn": "VendedorId",
            "summarizeBy": "count"
          },
          {
            "name": "CNPJ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f33a482b-aece-42b9-a0f6-4bcce8401eb7",
            "sourceColumn": "CNPJ",
            "summarizeBy": "none"
          },
          {
            "name": "StatusCredito",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f610311b-3944-4ab4-a95a-a8993953acbe",
            "sourceColumn": "StatusCredito",
            "summarizeBy": "none"
          },
          {
            "name": "DescCanalGerencial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b0098718-20fc-4e01-aaaa-8891262d213a",
            "sourceColumn": "DescCanalGerencial",
            "summarizeBy": "none"
          },
          {
            "name": "DescSubCanalGerencial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1099332c-2345-444f-9a02-699934cb4241",
            "sourceColumn": "DescSubCanalGerencial",
            "summarizeBy": "none"
          },
          {
            "name": "dataimplantacao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "c7f7760c-f256-4996-ba34-b90bc9f9f8a3",
            "sourceColumn": "dataimplantacao",
            "summarizeBy": "none"
          },
          {
            "name": "programa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e9e5bf6-3a2b-4ae4-98d7-19f0a2aabb62",
            "sourceColumn": "programa",
            "summarizeBy": "none"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR(dClientes[dataimplantacao])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "1915a11e-2a13-4d06-ab36-1b0180d95cb9",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Ativo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9d51f704-6799-48bd-882c-148ebff68a78",
            "sourceColumn": "Ativo",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "ebc1c7ed-d5c2-4f4a-9b6f-1471951fa845",
        "partitions": [
          {
            "name": "dClientes",
            "mode": "import",
            "queryGroup": "Servidor",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(Servidor, Banco),",
                "    bi_view_EmitenteAtivo = Fonte{[Schema=\"bi\",Item=\"view_EmitenteAtivo\"]}[Data],",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(bi_view_EmitenteAtivo,{\"Estado\", \"Endereco\"}),",
                "    #\"Texto em Maiúscula\" = Table.TransformColumns(#\"Colunas Removidas\",{{\"Bairro\", Text.Upper, type text}, {\"Cidade\", Text.Upper, type text}, {\"UF\", Text.Upper, type text}}),",
                "    #\"Erros Removidos\" = Table.RemoveRowsWithErrors(#\"Texto em Maiúscula\", {\"Cidade\"}),",
                "    #\"Linhas em Branco Removidas\" = Table.SelectRows(#\"Erros Removidos\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Linhas em Branco Removidas1\" = Table.SelectRows(#\"Linhas em Branco Removidas\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Linhas em Branco Removidas2\" = Table.SelectRows(#\"Linhas em Branco Removidas1\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Colunas Removidas1\" = Table.RemoveColumns(#\"Linhas em Branco Removidas2\",{\"CodigoMatriz\", \"IE\", \"NomeAbreviado\", \"LimiteCredito\", \"TipoEmitente\", \"cep\", \"dataUltCompra\", \"CODADM\", \"CODADMUF\", \"CodRede\"}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Colunas Removidas1\",{{\"dataimplantacao\", type date}}),",
                "    #\"Colunas Removidas2\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"nomeAjustado\"})",
                "in",
                "    #\"Colunas Removidas2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dUnidade",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "subEmpresaid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "31f32a3c-2dce-4d43-b77d-b37e1a738f54",
            "sourceColumn": "subEmpresaid",
            "summarizeBy": "none"
          },
          {
            "name": "Denominacao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "739520ca-c580-4702-a03e-b5d3de7a0994",
            "sourceColumn": "Denominacao",
            "summarizeBy": "none"
          },
          {
            "name": "Uni2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(dUnidade[Denominacao] = \"HIG\", \"ASA\", dUnidade[Denominacao])",
            "isDataTypeInferred": true,
            "lineageTag": "6c1bd8b4-f478-43a2-b86a-784cb8de7fb9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "52263d66-2012-4e5b-993c-50fa42f7d5b0",
        "partitions": [
          {
            "name": "dUnidade",
            "mode": "import",
            "queryGroup": "Bases Manuais",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(Servidor, Banco),",
                "    bi_view_EmpresaSubempresa = Fonte{[Schema=\"bi\",Item=\"view_EmpresaSubempresa\"]}[Data]",
                "in",
                "    bi_view_EmpresaSubempresa"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fConsolidado_Faturamento",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "QtdVendida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "a07ae97a-8f80-4326-a39e-288d723e1b94",
            "sourceColumn": "QtdVendida",
            "summarizeBy": "sum"
          },
          {
            "name": "QtdBonificada",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "534a19d0-bd5f-4266-8b24-68001e13a55d",
            "sourceColumn": "QtdBonificada",
            "summarizeBy": "sum"
          },
          {
            "name": "QtdDevolvida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "6b743714-11da-41c8-bcad-ea279cc96fc4",
            "sourceColumn": "QtdDevolvida",
            "summarizeBy": "sum"
          },
          {
            "name": "ValorTotal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "ba90e54f-1978-48b3-a582-9161b2ece145",
            "sourceColumn": "ValorTotal",
            "summarizeBy": "sum"
          },
          {
            "name": "ValorMercadoriaLiquido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "d3dadd06-20f0-45fa-add8-9b7173569670",
            "sourceColumn": "ValorMercadoriaLiquido",
            "summarizeBy": "sum"
          },
          {
            "name": "Peso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "02a2628b-abb5-45c5-b33b-b50d5409386a",
            "sourceColumn": "Peso",
            "summarizeBy": "sum"
          },
          {
            "name": "ValorLiquido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "0d55045d-d3df-46db-93c1-e600dd692ac2",
            "sourceColumn": "ValorLiquido",
            "summarizeBy": "sum"
          },
          {
            "name": "ValorDevolvido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "245b35b2-4191-4a00-ac68-34eed4b0f57f",
            "sourceColumn": "ValorDevolvido",
            "summarizeBy": "sum"
          },
          {
            "name": "FAT LIQUIDO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "dd57b8fe-95c2-4b70-a54a-8e9811ed40b8",
            "sourceColumn": "FAT LIQUIDO",
            "summarizeBy": "sum"
          },
          {
            "name": "QuantidadeLiquida",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "7061640b-9634-4a28-aa19-8217c30bd585",
            "sourceColumn": "QuantidadeLiquida",
            "summarizeBy": "sum"
          },
          {
            "name": "NumeroPedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "abe1aaa9-bcfb-4635-bb3f-44908323a373",
            "sourceColumn": "NumeroPedido",
            "summarizeBy": "sum"
          },
          {
            "name": "subEmpresaID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "efd3a27c-87a3-43fe-a1ca-2c34c21e10a3",
            "sourceColumn": "subEmpresaID",
            "summarizeBy": "count"
          },
          {
            "name": "EmpresaID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1c8bb61f-5d77-45be-b6df-628bbb96215e",
            "sourceColumn": "EmpresaID",
            "summarizeBy": "count"
          },
          {
            "name": "produtoID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4ad5cb70-5c3a-4110-a4e5-eb47b6f5527b",
            "sourceColumn": "produtoID",
            "summarizeBy": "none"
          },
          {
            "name": "vendedorID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "769c7fa8-f08f-4907-9449-4de9884d4fe6",
            "sourceColumn": "vendedorID",
            "summarizeBy": "none"
          },
          {
            "name": "emitenteID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a700b36d-96ef-4ca3-98f3-a24fbb35c9d5",
            "sourceColumn": "emitenteID",
            "summarizeBy": "none"
          },
          {
            "name": "Consolidacao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a5311ee6-1d1f-449d-b061-4a1ba2891b24",
            "sourceColumn": "Consolidacao",
            "summarizeBy": "sum"
          },
          {
            "name": "DataFaturamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "551357ae-ee9a-4100-ad64-6eac63776696",
            "sourceColumn": "DataFaturamento",
            "summarizeBy": "none"
          },
          {
            "name": "ClipoCliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "be2991aa-9c21-4931-a1a6-ec855e29466e",
            "sourceColumn": "ClipoCliente",
            "summarizeBy": "none"
          },
          {
            "name": "Estabelecimentoid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f8b59b70-d516-4eaa-81c9-458691206bf5",
            "sourceColumn": "Estabelecimentoid",
            "summarizeBy": "none"
          },
          {
            "name": "ProdutoPerfilEstrategico",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29324521-ab6d-4a45-81c6-f193ac84a9cc",
            "sourceColumn": "ProdutoPerfilEstrategico",
            "summarizeBy": "none"
          },
          {
            "name": "Devol ton",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "fConsolidado_Faturamento[QtdDevolvida] * RELATED(dProduto[PesoKG])/1000*-1"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "3a8c2be6-6564-44da-b52f-5a3bc6beb4a2",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "NatOper",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4157f593-a95a-4988-8155-3c4687f35743",
            "sourceColumn": "NatOper",
            "summarizeBy": "none"
          },
          {
            "name": "Vendedor Aux 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "037d46db-11b2-48a9-b660-e50068dabb9b",
            "sourceColumn": "Vendedor Aux 2",
            "summarizeBy": "sum"
          },
          {
            "name": "Fabrica",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "94e89162-9e14-4817-9cee-fcaa2f5634bd",
            "sourceColumn": "Fabrica",
            "summarizeBy": "none"
          },
          {
            "name": "Vend Aux 3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(), ",
              "    fConsolidado_Faturamento[emitenteID] = 744148 && fConsolidado_Faturamento[Fabrica] = \"VIT\", 1540,",
              "    fConsolidado_Faturamento[emitenteID] = 744148 && fConsolidado_Faturamento[Fabrica] = \"ASA\", 1563,",
              "    fConsolidado_Faturamento[emitenteID] = 744148 && fConsolidado_Faturamento[Fabrica] = \"PAL\", 1563,",
              "    fConsolidado_Faturamento[Vendedor Aux 2])"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "0680fc26-c5b1-4650-b733-1661537f1762",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "UltimaAtualizacao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57adfd60-3dce-4f4a-97e0-333d3e596cfa",
            "sourceColumn": "UltimaAtualizacao",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e3a3c027-4219-4511-a537-c9eac1ca7872",
        "partitions": [
          {
            "name": "fConsolidado_Faturamento",
            "mode": "import",
            "queryGroup": "Servidor",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(Servidor, Banco),",
                "    bi_view_notafiscalItem = Fonte{[Schema=\"bi\",Item=\"view_notafiscalItem\"]}[Data],",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(bi_view_notafiscalItem,{\"IPI\", \"ICMSSUB\", \"ICMS\", \"ICMSSNT\", \"ICMSSou\", \"OrigemDevolucao\", \"CanalGerencial\", \"codLoja\", \"Pis\", \"Descricao\"}),",
                "    #\"Coluna Condicional Adicionada\" = Table.AddColumn(#\"Colunas Removidas\", \"Vendedor Aux 2\", each if [NatOper] = \"611CEX\" then 1618 else if [NatOper] = \"6109RR\" then 1618 else if [NatOper] = \"232AMP\" then 1618 else if [NatOper] = \"2503\" then 1618 else [vendedorID]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Coluna Condicional Adicionada\",{{\"Vendedor Aux 2\", Int64.Type}}),",
                "    #\"Consultas Mescladas\" = Table.NestedJoin(#\"Tipo Alterado\", {\"produtoID\"}, dProduto, {\"ProdutoId\"}, \"dProduto\", JoinKind.LeftOuter),",
                "    #\"dProduto Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas\", \"dProduto\", {\"Fabrica\"}, {\"Fabrica\"}),",
                "    #\"Colunas Removidas1\" = Table.RemoveColumns(#\"dProduto Expandido\",{\"NotaFiscalid\", \"notafiscalitemid\", \"Origemid\", \"ValorBruto\"})",
                "in",
                "    #\"Colunas Removidas1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dProduto",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Codigo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0724e245-8f7a-4e87-a1e9-1cafa72a2822",
            "sourceColumn": "Codigo",
            "summarizeBy": "sum"
          },
          {
            "name": "Denominacao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6085942-1ad9-4117-bb5c-a2c8bc439c3d",
            "sourceColumn": "Denominacao",
            "summarizeBy": "none"
          },
          {
            "name": "PesoKG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "d1c18286-8359-4e70-b5d7-d4751f41a25d",
            "sourceColumn": "PesoKG",
            "summarizeBy": "sum"
          },
          {
            "name": "Marca",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "f27d4f33-b10b-4bb6-a061-7a9a9e8525c6",
            "sourceColumn": "Marca",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b6a65e8-b2dc-4585-aded-e84e4c9dc7cb",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "ProdutoId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "66083a6c-c89b-44ba-9891-6c2a19b0ddc2",
            "sourceColumn": "ProdutoId",
            "summarizeBy": "none"
          },
          {
            "name": "Fabrica",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8dc9ac76-0e6e-4674-9fb5-1c4a4fe0cc4e",
            "sourceColumn": "Fabrica",
            "summarizeBy": "none"
          },
          {
            "name": "CATEGORIA GERAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "23c449c5-1d42-4993-af2e-f825f964dd1e",
            "sourceColumn": "CATEGORIA GERAL",
            "summarizeBy": "none"
          },
          {
            "name": "SubCategoria1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "be20a500-f924-4a79-bddd-f91c6603fc54",
            "sourceColumn": "SubCategoria1",
            "summarizeBy": "none"
          },
          {
            "name": "ESTRATEGICO MACRO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1815a483-e981-475d-a3e3-6be1f53578da",
            "sourceColumn": "ESTRATEGICO MACRO",
            "summarizeBy": "none"
          },
          {
            "name": "CATTÁTICOS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e337222-47ab-4d95-b928-907fa79b81de",
            "sourceColumn": "CATTÁTICOS",
            "summarizeBy": "none"
          },
          {
            "name": "Categoria2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b8c9b1f9-3c20-4494-84c7-5ee150692e29",
            "sourceColumn": "Categoria2",
            "summarizeBy": "none"
          },
          {
            "name": "CATEGORIA EST MULTI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01627662-9d62-4943-91ee-fb1ab8084730",
            "sourceColumn": "CATEGORIA EST MULTI",
            "summarizeBy": "none"
          },
          {
            "name": "CATEGORIA EST VAREJO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3544ab49-cc4a-4a10-b9d7-2a01c7b08f1e",
            "sourceColumn": "CATEGORIA EST VAREJO",
            "summarizeBy": "none"
          },
          {
            "name": "CATEGORIA EST SUDESTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "524178e9-1854-4793-a73d-7f55b48f1632",
            "sourceColumn": "CATEGORIA EST SUDESTE",
            "summarizeBy": "none"
          },
          {
            "name": "REGIONAL CE - CE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a790f102-d62a-41ea-84fb-af3e81b85016",
            "sourceColumn": "REGIONAL CE - CE",
            "summarizeBy": "none"
          },
          {
            "name": "REGIONAL CE - MA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "410041f9-db98-4b7e-ac1e-3e4409890026",
            "sourceColumn": "REGIONAL CE - MA",
            "summarizeBy": "none"
          },
          {
            "name": "REGIONAL NO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da4b7fc8-2f19-4a97-8aac-503fda4a1ffc",
            "sourceColumn": "REGIONAL NO",
            "summarizeBy": "none"
          },
          {
            "name": "REGIONAL BA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04e4a9c4-d9a1-42bf-b00f-b48377d4b75f",
            "sourceColumn": "REGIONAL BA",
            "summarizeBy": "none"
          },
          {
            "name": "VAREJO PE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a52c42b6-170d-4c09-b4c9-c89f66090ad8",
            "sourceColumn": "VAREJO PE",
            "summarizeBy": "none"
          },
          {
            "name": "VAREJO AL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "904354ff-fb0e-4e32-97b7-aea43639bce0",
            "sourceColumn": "VAREJO AL",
            "summarizeBy": "none"
          },
          {
            "name": "VAREJO PB",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d7d67df7-273b-4775-ad8e-9591d9bfbb4b",
            "sourceColumn": "VAREJO PB",
            "summarizeBy": "none"
          },
          {
            "name": "VAREJO CE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ae07e43-b449-4661-8b97-c2e58828f608",
            "sourceColumn": "VAREJO CE",
            "summarizeBy": "none"
          },
          {
            "name": "VAREJO RN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34b0cfdd-ddb0-4e9a-a8f8-04d74fb8d1e3",
            "sourceColumn": "VAREJO RN",
            "summarizeBy": "none"
          },
          {
            "name": "REGIONAL SP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e8e6857-f78c-4ac2-bb6c-aaa0dce3cf04",
            "sourceColumn": "REGIONAL SP",
            "summarizeBy": "none"
          },
          {
            "name": "REGIONAL RJ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76562d71-cb14-422e-af5e-c0fdd84ea77b",
            "sourceColumn": "REGIONAL RJ",
            "summarizeBy": "none"
          },
          {
            "name": "ABC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    [Pareto Produto] >= 0.95, \"C\",",
              "    [Pareto Produto] >= 0.80, \"B\",",
              "    \"A\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "4efdd4a7-a7ac-4c2d-8071-aeaf7fbc34be",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "DesprezaProduto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3069599f-6bfa-420f-8908-947e26dd2320",
            "sourceColumn": "DesprezaProduto",
            "summarizeBy": "none"
          },
          {
            "name": "CatPcp",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6272904-3885-432a-aada-89fb9a152e21",
            "sourceColumn": "CatPcp",
            "summarizeBy": "none"
          },
          {
            "name": "PLT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c9babeb8-90f2-485c-9981-ffe14388a178",
            "sourceColumn": "PLT",
            "summarizeBy": "sum"
          },
          {
            "name": "UnidadeFabril",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecef1268-2835-44ed-a8d4-f467abdc9861",
            "sourceColumn": "UnidadeFabril",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b8f51eda-2c0e-4d40-af6f-c954d7dbd662",
        "partitions": [
          {
            "name": "dProduto",
            "mode": "import",
            "queryGroup": "Bases Manuais",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(Servidor, Banco),",
                "    bi_view_Produto = Fonte{[Schema=\"bi\",Item=\"view_Produto\"]}[Data],",
                "    #\"Valor Substituído\" = Table.ReplaceValue(bi_view_Produto,\"PÓ BTV LAVANDA 5KG\",\"PÓ BTV 5KG\",Replacer.ReplaceText,{\"SubCategoria1\"}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Valor Substituído\",{{\"Codigo\", Int64.Type}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Meta",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "f1f7c550-f9d2-40d6-80df-6c29d52779a8",
            "sourceColumn": "Data",
            "summarizeBy": "none"
          },
          {
            "name": "EmpresaId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ea11c77c-dab3-435b-9185-6b7f02568791",
            "sourceColumn": "EmpresaId",
            "summarizeBy": "none"
          },
          {
            "name": "ProdutoId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3c8a348f-01a6-4d55-af9f-e67a78085074",
            "sourceColumn": "ProdutoId",
            "summarizeBy": "none"
          },
          {
            "name": "Valor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "0.00",
            "lineageTag": "f5acd434-b381-4117-ae45-66918d5d9019",
            "sourceColumn": "Valor",
            "summarizeBy": "sum"
          },
          {
            "name": "TipoMeta",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "6f930ce6-0721-4628-a4d6-1dc782dfa8d9",
            "sourceColumn": "TipoMeta",
            "summarizeBy": "none"
          },
          {
            "name": "Vendedorid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5f3f5a76-9dff-4332-92db-5861ec426b72",
            "sourceColumn": "Vendedorid",
            "summarizeBy": "none"
          },
          {
            "name": "PerfilEstrategico",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5eca9cf5-1bbb-4019-8f18-0eeec3476b88",
            "sourceColumn": "PerfilEstrategico",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b8642669-64c7-404e-b6b5-d3592d236468",
        "partitions": [
          {
            "name": "Meta",
            "mode": "import",
            "queryGroup": "Bases Manuais",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(Servidor, Banco),",
                "    bi_view_MetaPIG = Fonte{[Schema=\"bi\",Item=\"view_MetaPIG\"]}[Data],",
                "    #\"Valor Substituído\" = Table.ReplaceValue(bi_view_MetaPIG,null,\"ESTRATEGICO\",Replacer.ReplaceValue,{\"TipoMeta\"})",
                "in",
                "    #\"Valor Substituído\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dCanal_de vendas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "CLIPO CLIENTE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "402e5aee-9d57-4dd7-b87c-68cdbedd2109",
            "sourceColumn": "CLIPO CLIENTE",
            "summarizeBy": "none"
          },
          {
            "name": "CANAL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "8aa8c0c8-bce8-4b56-a0b6-fcde3bd5a9d7",
            "sourceColumn": "CANAL",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "230541bc-19dc-4f34-90ed-732b014a3dc2",
        "measures": [
          {
            "name": "Fat R$ Display",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR Fat = [FatR$]",
              "return if(ISBLANK(Fat) ,\"\",Fat)"
            ],
            "lineageTag": "4ef3815c-7402-4642-9c3f-6829bdc162c7"
          }
        ],
        "partitions": [
          {
            "name": "dCanal_de vendas",
            "mode": "import",
            "queryGroup": "Bases Manuais",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(Servidor, Banco),",
                "    bi_view_MetaPIG = Fonte{[Schema=\"bi\",Item=\"VIEW_CANALVENDA\"]}[Data]",
                "in",
                "    bi_view_MetaPIG"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas_Fat",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "925abdd7-3180-4ebe-b39d-1677dd61587c",
        "measures": [
          {
            "name": "FatR$",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "SUM(fConsolidado_Faturamento[FAT LIQUIDO])"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "21be323a-21e8-4a46-a80f-4e3c5354dcb6"
          },
          {
            "name": "LY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "CALCULATE(",
              "    Medidas_Fat[FatR$], SAMEPERIODLASTYEAR(Calendario[Data]))"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "f4fa6e48-6528-4767-af5c-29eb725e82f9"
          },
          {
            "name": "YoY",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR varENTRADA = [LY]",
              "VAR varResultado = ",
              "DIVIDE(",
              "    Medidas_Fat[FatR$]- varENTRADA, varENTRADA)",
              "VAR varFormato = FORMAT(varResultado, \"#%\")",
              "    RETURN",
              "    IF(varResultado = BLANK(), \"🟢\"&varFormato, IF(varResultado > 0, \"🟢\"&varFormato, \"🔴\"&varFormato))"
            ],
            "lineageTag": "662ed9fb-dc65-4ec0-a5e1-58e9ab17db85"
          },
          {
            "name": "M-LY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "[FatR$],",
              "    DATEADD(Calendario[Data],",
              "    -1,",
              "    YEAR",
              "    )",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "5b9ca7a9-10e3-4ffb-ab7b-01b06bf8145d"
          },
          {
            "name": "M-1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "[FatR$],",
              "    DATEADD(Calendario[Data],",
              "    -1,",
              "    MONTH",
              "    ))"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "97dcd9f2-3e36-461d-ba4a-a34e20363ea4"
          },
          {
            "name": "Meta R$",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "CALCULATE(SUM(Meta[Valor]), Meta[TipoMeta] = \"Financeira\")",
              ""
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "b9de3eec-249b-4bae-ae72-b463085172a3"
          },
          {
            "name": "% Aderencia",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE(Medidas_Fat[FatR$], [Meta R$])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "da84b23a-b403-4a05-b741-4058c11b2689"
          },
          {
            "name": "% M-1",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "",
              "VAR  Divisao = DIVIDE([FatR$],[M-1])-1",
              "RETURN",
              "IF(Divisao = -1, BLANK(), Divisao)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "754d5178-4728-4c84-8c04-29a9a074c06e"
          },
          {
            "name": "% M-LY",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR  Divisao = DIVIDE([FatR$],[M-LY])-1",
              "RETURN",
              "IF(Divisao = -1, BLANK(), Divisao)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "4446b898-21f2-4995-af10-a847b9a8c6d3"
          },
          {
            "name": "Qt Fat",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              " SUM(fConsolidado_Faturamento[QuantidadeLiquida])",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "9b0276a2-5211-4eba-8e73-1fbb719757f2"
          },
          {
            "name": "Meta Vol",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              " CALCULATE(SUM(Meta[Valor]), Meta[TipoMeta] = \"Vol\")",
              "",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "5780c2c1-3252-4b49-acd3-14ef962a3902"
          },
          {
            "name": "Qt M-LY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "[Qt Fat],",
              "    DATEADD(Calendario[Data],",
              "    -1,",
              "    YEAR",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "f32065b4-bbcb-4062-a477-880f44aabce3"
          },
          {
            "name": "Qt M-1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "[Qt Fat],",
              "    DATEADD(Calendario[Data],",
              "    -1,",
              "    MONTH",
              "    ))"
            ],
            "formatString": "#,0",
            "lineageTag": "140248a0-58a4-4608-ba27-df610e84b081"
          },
          {
            "name": "%Qt",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE([Qt Fat],[Meta Vol])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b9730758-35b8-4e9e-b10b-7a18a2af3c91"
          },
          {
            "name": "% M-1 qt",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "",
              "VAR  Divisao = DIVIDE([Qt Fat],[Qt M-1])-1",
              "RETURN",
              "IF(Divisao = -1, BLANK(), Divisao)",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e9a6ff9d-679b-49a0-87b9-63a2765a234d"
          },
          {
            "name": "% M-LY qt",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "",
              "VAR  Divisao = DIVIDE([Qt Fat],[Meta Vol])-1",
              "RETURN",
              "IF(Divisao = -1, BLANK(), Divisao)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f07df3f9-a1cd-4752-8e61-f0f874919970"
          },
          {
            "name": "Em Aberto M-1 R$",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "CALCULATE([Carteira Aberta] ,all(Calendario), fMonitorPedido[DataImplant] <=  EOMONTH( max(Calendario[Data]) ,-1) )",
            "lineageTag": "68c691ea-82f7-4934-91b3-2fde684e30bc"
          },
          {
            "name": "Variação Faturamento",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR  Divisao = DIVIDE([FatR$],[LY])-1",
              "RETURN",
              "IF(Divisao = -1, BLANK(), Divisao)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e68ad001-4afe-43d2-90d3-a19975e9c1b0"
          },
          {
            "name": "%MoM",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR varfattMoM = [M-1]",
              "VAR varResultado = ",
              "DIVIDE([FatR$] - varfattMoM, varfattMoM)",
              "     ",
              "     RETURN",
              "          varResultado"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a400997a-948d-433d-9709-35b792d6e203"
          },
          {
            "name": "Detalhe MoM %",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "FORMAT(",
              "    [%MoM], \"⇡ 0%;  ⇣ 0%\")"
            ],
            "lineageTag": "ec64460c-fc9f-41a7-be6b-939f7ea130a3"
          },
          {
            "name": "%YoY",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR varFatYoY = [LY]",
              "VAR varResultado = ",
              "DIVIDE([FatR$] - varFatYoY, varFatYoY)",
              "     ",
              "     RETURN",
              "          varResultado"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "faff9bd0-2a5c-4e50-8774-eb9d0add3b52"
          },
          {
            "name": "Detalhe YoY %",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "FORMAT(",
              "    [%YoY], \"▲ 0.00%;  ▼ 0.00%\")"
            ],
            "lineageTag": "acb6f133-ff38-4106-b7a1-605c2f5c507a"
          },
          {
            "name": "Em Aberto qt M-1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Qt Cart] ,all(Calendario), fMonitorPedido[DataImplant] <=  EOMONTH( max(Calendario[Data]) ,-1) )",
            "lineageTag": "ddc22771-da41-4338-b375-f9ba037a33dd"
          },
          {
            "name": "Fatmes",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(Medidas_Fat[FatR$], FILTER(Calendario, Calendario[Mês] = 1))",
            "lineageTag": "a0ee4896-cb5c-48c1-b4a8-cf61f2a15b62"
          },
          {
            "name": "Meta faseamento",
            "expression": "0.40",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d4d125fa-7dd8-41bb-83d6-65f0fe1e11bc"
          },
          {
            "name": "Fat faseamento",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE([FatR$], DATESBETWEEN(Calendario[Data], DATE(2024,08,01), DATE(2024,08,15)))"
            ],
            "lineageTag": "14dfd150-44c9-4f7b-ab0b-803ef5985b31"
          },
          {
            "name": "%Faseamento",
            "expression": [
              "",
              "DIVIDE([FatR$], [Meta R$])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3dd8cd26-5ecb-4e96-872c-37e78f7fa828"
          },
          {
            "name": "%Estrategicob",
            "expression": "DIVIDE([Qt Fat], [Meta Estrat])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "92497d96-9304-4770-a0b3-9ce48c9badea"
          },
          {
            "name": "Meta Estrat",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(Meta[Valor]), Meta[TipoMeta] = \"ESTRATEGICO\")",
            "formatString": "#,0",
            "lineageTag": "29abfca2-58c0-48c0-84b2-b0c0b84e84a6"
          },
          {
            "name": "FAT D-1",
            "expression": [
              "CALCULATE(",
              "[FatR$],",
              "    MAX(Calendario[Mês 1], -2))"
            ],
            "formatString": "0",
            "lineageTag": "6b1bd583-7578-461d-9fc2-5c65e6487a57"
          },
          {
            "name": "Fat Acumulado",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE([FatR$], ",
              "    FILTER(ALLSELECTED(Calendario), ",
              "       Calendario[Data]<= MAX(Calendario[Data])",
              "  )",
              ")"
            ],
            "lineageTag": "fbc2a449-edcc-4ab4-b719-c7b634b81bca"
          },
          {
            "name": "M-LY qt",
            "expression": [
              "",
              "",
              "VAR varFatYoY = [Qt M-LY]",
              "VAR varResultado = ",
              "DIVIDE([Qt Fat] - varFatYoY, varFatYoY)",
              "     ",
              "     RETURN",
              "          varResultado"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "00aa566e-493b-4860-a4f6-a62e588c3f8b"
          },
          {
            "name": "Detalhe YoY% qt",
            "expression": [
              "FORMAT(",
              "    [% M-LY qt2], \"▲ 0.00%;  ▼ 0.00%\")"
            ],
            "lineageTag": "e79e5075-ed68-4045-8a03-0d53a7dcc779"
          },
          {
            "name": "Fat Lanç",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(SUM(fConsolidado_Faturamento[FAT LIQUIDO]), dProduto[Status] = \"LANÇAMENTO\")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "73e609ba-ed4e-4949-9a03-70533902cc43"
          },
          {
            "name": "Aderencia Lanç",
            "expression": [
              "",
              "DIVIDE(CALCULATE([FatR$], dProduto[Status] = \"LANÇAMENTO\"), CALCULATE([FatR$], ALL(dProduto)))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "eba11360-93ce-4e73-8abc-11faba559e5a"
          },
          {
            "name": "FatR$2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(SUM(fConsolidado_Faturamento[FAT LIQUIDO]),ALL(dProduto[Denominacao]))"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "9a83c23d-22ca-4034-a991-d59fb075dcc8"
          },
          {
            "name": "% M-LY qt2",
            "expression": [
              "",
              "",
              "VAR  Divisao = DIVIDE([Qt Fat],[Qt M-LY])-1",
              "RETURN",
              "IF(Divisao = -1, BLANK(), Divisao)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "03e35689-96a9-4f77-882a-3df58f108cae"
          },
          {
            "name": "Qt M-LY Travado",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "[Qt Fat],",
              "    DATEADD(Calendario[Data],",
              "    -1,",
              "    YEAR",
              "    ), ALL(Calendario[Data]))"
            ],
            "lineageTag": "63996b42-a136-4b1c-b0db-8f01520fd31a"
          },
          {
            "name": "Media qt fat 2023",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE([Qt Fat]/9)"
            ],
            "lineageTag": "7cca1159-9956-43c3-833d-6a2110cea763"
          },
          {
            "name": "Media qt fat 2024",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE([Qt Fat]/10)"
            ],
            "lineageTag": "702ed649-3f1b-40a7-ac07-f3eede2f53cd"
          },
          {
            "name": "Media QT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "AVERAGEX(VALUES(Calendario[Ano/Mês]), [Qt Fat])"
            ],
            "lineageTag": "2ea3d408-5d78-40b2-bf48-931343279260"
          }
        ],
        "partitions": [
          {
            "name": "Medidas_Fat",
            "mode": "import",
            "queryGroup": "Medidas",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Coluna 1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas_Cart",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "991e6419-3937-4124-bb80-68fb68034bc9",
        "measures": [
          {
            "name": "Carteira Aberta",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "SUM(fMonitorPedido[Vl Líq Aberto])",
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "ea1c12f9-c0d6-4cb9-9b68-4cdfd95e1ec5"
          },
          {
            "name": "Entrada Carteira",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SUM(fMonitorPedido[Vl Líquido])",
              ""
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "10f68d78-1e6c-4c0c-a770-365d2972fad3"
          },
          {
            "name": "Fat+Cart",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "[FatR$]+[Total Aberto]",
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "60f00fec-11a1-4128-9f41-763a005392e7"
          },
          {
            "name": "%Fat+Cart",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE([Fat+Cart],[Meta R$])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "b350b66e-62d3-4bb8-8ee6-95f60047af74"
          },
          {
            "name": "Qt Cart",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              " CALCULATE(SUM(fMonitorPedido[QtdAberta]))",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "ed4565b6-6fc7-4f78-a970-5379941dd37c"
          },
          {
            "name": "Qt Cart+Fat",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "[Total Abertoqt]+[Qt Fat]",
            "formatString": "#,0",
            "lineageTag": "d19921cd-e880-4b4a-9bb7-f7744fb3fd2b"
          },
          {
            "name": "%Fat+Cartqt",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE([Qt Cart+Fat],[Meta Vol])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3b9d01e5-6c5d-413e-82e5-0aa7ed11c413"
          },
          {
            "name": "Gap",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "IF(",
              "    [Fat+Cart]-[Meta R$]>0, \"\", [Meta R$]-[Fat+Cart])"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "884bb174-33cf-4152-976b-9aa4bab3998b"
          },
          {
            "name": "Total Aberto",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              " VAR varSum = [Carteira Aberta] + [Em Aberto M-1 R$]",
              " RETURN",
              " IF(varSum = BLANK(), 0, varSum)"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "3f21dd3c-2fd2-4661-97d7-93852576e469"
          },
          {
            "name": "CART %MoM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR varfattMoM = [M-1]",
              "VAR varResultado = ",
              "DIVIDE([FatR$] - varfattMoM, varfattMoM)",
              "     ",
              "     RETURN",
              "          varResultado"
            ],
            "lineageTag": "eba78cdc-1fbf-4f01-b81a-6dca84fea54e"
          },
          {
            "name": "C Detalhe MoM %",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "FORMAT(",
              "    Medidas_Cart[CART %MoM], \"⇡ 0%;  ⇣ 0%\")"
            ],
            "lineageTag": "a204c621-7056-4783-9d8a-dc31e8bd82a5"
          },
          {
            "name": "Total Abertoqt",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "Medidas_Cart[Qt Cart] + [Em Aberto qt M-1]",
            "formatString": "#,0",
            "lineageTag": "92568727-71be-45cd-a562-8b1d8fb8380a"
          },
          {
            "name": "Qt Cancelada",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "SUM(fMonitorPedido[QtdCancelada])",
            "formatString": "#,0",
            "lineageTag": "1ff66eb4-7f36-4cc7-a3ab-fc9eae1f6e16"
          },
          {
            "name": "Qt pedidos abertos",
            "expression": [
              "CALCULATE(DISTINCTCOUNT(fMonitorPedido[NumeroPedido]), ",
              "fMonitorPedido[QtdAberta] > 0)"
            ],
            "formatString": "0",
            "lineageTag": "c3e4fa67-e0a0-4f7b-b376-9d24f732c0e1"
          },
          {
            "name": "Cart.Aberto Ton",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR varpeso = SUM(fMonitorPedido[PesoLiqAberto])",
              "RETURN  ",
              "varpeso/1000"
            ],
            "lineageTag": "5bc47b15-1ef9-4133-9dc4-f9dde4673456"
          },
          {
            "name": "Cartab.ton M-1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(Medidas_Cart[Cart.Aberto Ton] ,all(Calendario), fMonitorPedido[DataImplant] <=  EOMONTH( max(Calendario[Data]) ,-1) )",
            "lineageTag": "eb55092f-0c0e-4339-8bf9-08e452693ab3"
          },
          {
            "name": "Cart Ton",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "Medidas_Cart[Cartab.ton M-1]+Medidas_Cart[Cart.Aberto Ton]",
            "formatString": "#,0",
            "lineageTag": "a2958d07-e91e-4059-8150-db7e35942945"
          },
          {
            "name": "Fat+CartTon",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "Medidas_Cart[Cart Ton]+Medidas_Ton[Qt Ton]",
            "formatString": "#,0",
            "lineageTag": "bb246266-c87a-43fb-80e4-1a5d71f45ed9"
          },
          {
            "name": "%Fat+Cartton",
            "expression": "DIVIDE([Fat+CartTon],[Meta Ton])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "184919d9-c765-45b0-9a0f-00e993ba95a6"
          },
          {
            "name": "GapTon",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "IF(",
              "    [Fat+CartTon]-[Meta Ton]>0, \"\", [Meta Ton]-[Fat+CartTon])"
            ],
            "formatString": "#,0",
            "lineageTag": "85b27fcd-6d50-4e68-a2e2-b973f405c687"
          },
          {
            "name": "Entrad qtd",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "SUM(fMonitorPedido[QtdPedida])",
            "formatString": "#,0",
            "lineageTag": "88a40e66-9486-44c3-81a0-96cc3b6114cb"
          },
          {
            "name": "RankingCartQt",
            "expression": "RANKX(ALL(dProduto), [Total Abertoqt])",
            "formatString": "0",
            "lineageTag": "eb04c438-475d-44d3-aac1-25521ae62202"
          },
          {
            "name": "RankingCartR$",
            "expression": "RANKX(ALL(dProduto), [Total Aberto])",
            "formatString": "0",
            "lineageTag": "13193f08-3ea0-4d10-a232-ada98b7fe5a3"
          },
          {
            "name": "Valor Cancelado",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "",
              "VAR varCancelado = SUM(fMonitorPedido[Valor Cancelado])",
              "RETURN",
              "IF(varCancelado = BLANK(), 0, varCancelado)",
              "   "
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "b0999721-0749-4689-a91d-ac1e783ae353"
          },
          {
            "name": "%Cancelamento",
            "expression": [
              "",
              "VAR varDivide = DIVIDE([Valor Cancelado], [Fatmes])",
              "RETURN",
              "IF(varDivide = 0, BLANK(), varDivide)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ab876e26-30e4-49ac-a3bc-83294d3d3c96"
          },
          {
            "name": "Totalaberto abs",
            "expression": [
              "",
              "VAR varCart = [Total Aberto]",
              "VAR varCartabs = CALCULATE([Total Aberto], ALLSELECTED(fMonitorPedido))",
              "RETURN",
              "DIVIDE(varCart, varCartabs)",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e1aadbdf-151a-40aa-93b8-84665a66034f"
          },
          {
            "name": "%Fat+Cartqtest",
            "expression": "DIVIDE([Qt Cart+Fat],[Meta Estrat])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "abe2a836-ec13-4ebf-9d8e-ba7041cdf0b7"
          },
          {
            "name": "Valor CanceladoGrafico",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              " SUM(fMonitorPedido[Valor Cancelado])",
              "",
              "   "
            ],
            "lineageTag": "d4282605-e265-4161-b586-86241be7f754"
          },
          {
            "name": "D-1 FAT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "",
              "VAR vDataContexto = CALCULATE(TODAY())",
              "VAR vUltimaDataFato = CALCULATE(",
              "    MAX(fConsolidado_Faturamento[DataFaturamento]), ",
              "    Calendario[Data] < vDataContexto)",
              "",
              "    VAR vValorUltimaData =",
              "    CALCULATE(",
              "        [FatR$],",
              "        Calendario[Data] = vUltimaDataFato",
              "    )",
              "    RETURN",
              "    vValorUltimaData"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "75d9b829-c86e-4224-bd43-a7c099a64a35"
          },
          {
            "name": "ENTRADA D-1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "",
              "VAR vDataContexto = CALCULATE(TODAY())",
              "VAR vUltimaDataFato = CALCULATE(",
              "    MAX(fMonitorPedido[DataImplant]), ",
              "    Calendario[Data] < vDataContexto)",
              "",
              "    VAR vValorUltimaData =",
              "    CALCULATE(",
              "        [Entrada Carteira],",
              "        Calendario[Data] = vUltimaDataFato",
              "    )",
              "    RETURN",
              "    vValorUltimaData",
              ""
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "4d0410f5-459e-47b8-a4a7-25bb51461310"
          },
          {
            "name": "DEVOLUÇÃO",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "",
              "SUM(fConsolidado_Faturamento[ValorDevolvido])*-1"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "7906839f-341f-4fed-b30c-4a93c73a66a4"
          },
          {
            "name": "Contagempedidos",
            "expression": "CALCULATE(DISTINCTCOUNT(fMonitorPedido[NumeroPedido]))",
            "formatString": "#,0",
            "lineageTag": "18b1c3ad-20e2-4977-9733-87bdb5dfaa82"
          },
          {
            "name": "E D-1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR vDataContexto = CALCULATE(TODAY())",
              "VAR vUltimaDataFato = CALCULATE(",
              "    MAX(fMonitorPedido[DataImplant]), ",
              "    Calendario[Data] < vDataContexto)",
              "",
              "    VAR vValorUltimaData =",
              "    CALCULATE(",
              "        [Entrada Carteira],",
              "        Calendario[Data] = vUltimaDataFato",
              "    )",
              "    RETURN",
              "    vValorUltimaData",
              ""
            ],
            "lineageTag": "1a451bea-3166-42ab-a6d6-c23ef2885d2e"
          },
          {
            "name": "DATA HOJE",
            "expression": [
              "",
              "CALCULATE(TODAY())"
            ],
            "formatString": "General Date",
            "lineageTag": "b630dea3-69e2-402e-8b5c-9ba56e892bed"
          },
          {
            "name": "Qt Pedidos",
            "expression": [
              "",
              "DISTINCTCOUNT(fMonitorPedido[NumeroPedido])"
            ],
            "formatString": "0",
            "lineageTag": "42f9c261-dd8a-46c7-b9d7-3d1a81154a48"
          },
          {
            "name": "SALDO",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "[Entrad qtd]-[Qt Cancelada]",
            "formatString": "#,0",
            "lineageTag": "96319073-baa7-41d1-90d4-6e3127c8bd92"
          },
          {
            "name": "Aging",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGE(fMonitorPedido[Aging pedidos])",
            "lineageTag": "14d7785f-cf4b-4f6d-86d3-cc436bbea250"
          }
        ],
        "partitions": [
          {
            "name": "Medidas_Cart",
            "mode": "import",
            "queryGroup": "Medidas",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Coluna 1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas_Posit",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "2274a0d9-c23b-458c-8750-f4add479e39b",
        "measures": [
          {
            "name": "posit2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              " VAR POSIT = CALCULATE(DISTINCTCOUNT(dClientes[Emitenteid]), FILTER(dClientes, [Qt Fat] > 0))",
              " RETURN",
              " IF(ISBLANK(POSIT), 0, POSIT)",
              "",
              " ",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "0ccaa341-8530-400c-9861-446f4546db67"
          },
          {
            "name": "posit2cart",
            "expression": [
              "",
              "CALCULATE(DISTINCTCOUNT(dClientes[Emitenteid]), ",
              "                   FILTER(dClientes, ",
              "                   Medidas_Posit[posit2] = 0 && [Total Abertoqt] > 0)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "96369698-2874-4a06-b4b6-ca6f7983a1c7"
          },
          {
            "name": "Meta Posit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(Meta[Valor]), Meta[TipoMeta] = \"POSITIVACAO\")",
            "formatString": "#,0",
            "lineageTag": "a378d620-62e5-4918-97eb-4847e6b80f83"
          },
          {
            "name": "Asa",
            "expression": "CALCULATE(Medidas_Posit[posit2], dUnidade[subEmpresaid]= 3)",
            "formatString": "#,0",
            "lineageTag": "73433d47-b726-4ccd-9319-b6e1f5524d31"
          },
          {
            "name": "Hig",
            "expression": "CALCULATE(Medidas_Posit[posit2], dUnidade[subEmpresaid] = 4)",
            "formatString": "#,0",
            "lineageTag": "0c2fa3be-f759-4165-abc7-73b023b90011"
          },
          {
            "name": "Pal",
            "expression": "CALCULATE(Medidas_Posit[posit2], dUnidade[subEmpresaid]= 5)",
            "formatString": "#,0",
            "lineageTag": "2a109473-2f49-4d2e-8448-8c59a012760d"
          },
          {
            "name": "Vit",
            "expression": "CALCULATE(Medidas_Posit[posit2], dUnidade[subEmpresaid]= 6)",
            "formatString": "#,0",
            "lineageTag": "124778e8-d5bf-4f22-93e7-696add7236f6"
          },
          {
            "name": "% Aderencia.posit",
            "expression": "DIVIDE(Medidas_Posit[posit2], [Meta Posit])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7a97d771-7675-4932-8e94-dcfefcc4f117"
          },
          {
            "name": "FAT+CARTPOSIT",
            "expression": "Medidas_Posit[posit2]+Medidas_Posit[posit2cart]",
            "formatString": "#,0",
            "lineageTag": "46353b12-36c6-48f3-b815-4345b13e7c24"
          },
          {
            "name": "Gapposit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "IF(",
              "    [FAT+CARTPOSIT]-[Meta Posit]>0, \"\", [Meta Posit]-[FAT+CARTPOSIT])"
            ],
            "formatString": "#,0",
            "lineageTag": "fd9cd131-19cb-41eb-b462-63f36d67f84e"
          },
          {
            "name": "Posit travado",
            "expression": [
              "",
              "   CALCULATE(Medidas_Posit[posit2], ALL('Estrategico Coord_Vend'), ALL(dProduto)",
              "",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "ddbff455-5002-47de-9920-5ee9330e4558"
          },
          {
            "name": "%Posit Estrategico",
            "expression": [
              "",
              "DIVIDE(Medidas_Posit[posit2], Medidas_Posit[Posit travado])",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "16cce038-b212-4476-a5b1-6926a502a662"
          },
          {
            "name": "Qt Atingida",
            "expression": [
              "",
              "VAR varTabelax = SUMMARIZE('Estrategico Coord_Vend',",
              "",
              "'Estrategico Coord_Vend'[Caracteristicaestrategico],",
              "",
              "\"Metricax\", SUM(fConsolidado_Faturamento[QuantidadeLiquida]),",
              "\"Metricay\", CALCULATE(SUM(Meta[Valor]), Meta[TipoMeta] = \"VOL\")",
              ")",
              "RETURN",
              "SUMX(varTabelax, IF(DIVIDE([Metricax], [Metricay]) >= 1,1,0))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "bb9d3d29-3e69-4492-b808-3716a63971f7"
          },
          {
            "name": "Media posit",
            "expression": [
              "",
              " ",
              "VAR varTabelax = ",
              "FILTER(SUMMARIZE('Estrategico Coord_Vend',",
              "'Estrategico Coord_Vend'[Caracteristicaestrategico],",
              "",
              "\"Metricax\", DIVIDE(Medidas_Posit[posit2],",
              "",
              "        Medidas_Posit[Posit travado]),",
              "",
              "        \"LINHA\", DISTINCTCOUNT('Estrategico Coord_Vend'[Caracteristicaestrategico])),",
              "        NOT(ISBLANK([Metricax])))",
              "        ",
              "    ",
              "        ",
              "        RETURN",
              "",
              "        AVERAGEX(varTabelax, DIVIDE([Metricax], [LINHA]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6c460658-71a7-44d0-8d66-863a8d3c7c5b"
          },
          {
            "name": "qt cat est",
            "expression": [
              "",
              "CALCULATE(DISTINCTCOUNT('Estrategico Coord_Vend'[Caracteristicaestrategico]))"
            ],
            "formatString": "0",
            "lineageTag": "bda2b3ad-30dd-48e6-b3e3-b181a3e0bb49"
          },
          {
            "name": "teste",
            "expression": [
              "",
              "IF(ISBLANK(Medidas_Posit[posit2]),0, Medidas_Posit[posit2])"
            ],
            "formatString": "0",
            "lineageTag": "4687e422-3cf7-4738-aa1b-6e2050eea550"
          },
          {
            "name": "Media posit Gerencia",
            "expression": [
              "",
              " ",
              "VAR varTabelax = ",
              "FILTER(SUMMARIZE('Estrategico_Gerencia',",
              "'Estrategico_Gerencia'[Categoria],",
              "",
              "\"Metricax\", DIVIDE(Medidas_Posit[posit2],",
              "",
              "        Medidas_Posit[Posit travado Ger]),",
              "",
              "        \"LINHA\", DISTINCTCOUNT('Estrategico_Gerencia'[Categoria])),",
              "        NOT(ISBLANK([Metricax])))",
              "        ",
              "    ",
              "        ",
              "        RETURN",
              "",
              "        AVERAGEX(varTabelax, DIVIDE([Metricax], [LINHA]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0de0cf48-b2cd-4120-b629-607572bc2834"
          },
          {
            "name": "Qt Atingida Ger",
            "expression": [
              "",
              "VAR varTabelax = SUMMARIZE('Estrategico_Gerencia',",
              "'Estrategico_Gerencia'[Categoria],",
              "\"Metricax\", SUM(fConsolidado_Faturamento[QuantidadeLiquida]),",
              "\"Metricay\", CALCULATE(SUM(Meta[Valor]), Meta[TipoMeta] = \"VOL\")",
              ")",
              "RETURN",
              "SUMX(varTabelax, IF(DIVIDE([Metricax], [Metricay]) >= 1,1,0))"
            ],
            "formatString": "0",
            "lineageTag": "5a816a24-0fb9-4568-88f5-cbf9170d0982"
          },
          {
            "name": "Posit travado Ger",
            "expression": [
              "",
              "   CALCULATE(Medidas_Posit[posit2], ALL(Estrategico_Gerencia), ALL(dProduto), ALL(dUnidade))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "9cf90a2e-a3dd-4066-90d5-81f866fd0f15"
          },
          {
            "name": "%Posit Estrategico ger",
            "expression": [
              "",
              "DIVIDE(Medidas_Posit[posit2], Medidas_Posit[Posit travado Ger])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "43cf299f-94cd-47ba-9e28-bf5697197766"
          },
          {
            "name": "TESTE4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SUM(Meta[Valor])",
            "lineageTag": "05fc787d-e1c0-4c3b-a248-b7686ed0eadd"
          },
          {
            "name": "POSIT+CART.POSIT",
            "expression": "Medidas_Posit[posit2]+Medidas_Posit[posit2cart]",
            "formatString": "0",
            "lineageTag": "8adaefee-e991-4555-b7b2-4da8f8159f5e"
          },
          {
            "name": "% POSIT + CART vs GERAL",
            "expression": [
              "",
              "DIVIDE(Medidas_Posit[POSIT+CART.POSIT], [Fat+CartPosit Travado])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7d5a5eb6-e0ce-456c-ac46-b43be591b3f2"
          },
          {
            "name": "% POSIT + CART vs GERAL GER",
            "expression": [
              "",
              "DIVIDE(Medidas_Posit[POSIT+CART.POSIT], [Fat+CartPosit Travado Ger])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0cf1cb64-4b18-4913-8bc0-4f9b6a7f3031"
          },
          {
            "name": "Fat+CartPosit Travado",
            "expression": [
              "",
              "",
              "CALCULATE([FAT+CARTPOSIT], ALL('Estrategico Coord_Vend'), ALL(dProduto))"
            ],
            "formatString": "0",
            "lineageTag": "fd66e613-3931-4bed-9cc7-4801d11e5340"
          },
          {
            "name": "Fat+CartPosit Travado Ger",
            "expression": [
              "",
              "",
              "CALCULATE([FAT+CARTPOSIT],  ALL(Estrategico_Gerencia), ALL(dProduto), ALL(dUnidade))"
            ],
            "formatString": "0",
            "lineageTag": "26facec7-bd67-4326-9db5-eb23ca7b280c"
          },
          {
            "name": "teste 2",
            "expression": [
              "",
              "CALCULATE(DISTINCTCOUNT('Estrategico Coord_Vend'[Caracteristicaestrategico]), FILTER(fConsolidado_Faturamento, [%Qt] > 0))"
            ],
            "formatString": "0",
            "lineageTag": "86888258-ac59-4e64-9a26-45ff0c981219"
          }
        ],
        "partitions": [
          {
            "name": "Medidas_Posit",
            "mode": "import",
            "queryGroup": "Medidas",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Coluna 1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas_YTG",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "lineageTag": "75738018-5954-467a-9d08-debae77b4282",
        "measures": [
          {
            "name": "Fat 2022",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "CALCULATE([FatR$], Calendario[Ano] = \"2022\")",
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "27f1cf50-95e9-4e03-86bb-3936db61bb3e"
          },
          {
            "name": "Fat 2023",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "CALCULATE([FatR$], Calendario[Ano] = \"2023\")",
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "6d5a3775-70b5-44bb-ba2b-35dee6c2778c"
          },
          {
            "name": "23vs22",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "",
              "VAR  Divisao = DIVIDE([Fat 2023],[Fat 2022])-1",
              "RETURN",
              "IF(Divisao = -1, BLANK(), Divisao)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "e5e78af4-553b-4bbe-a6a3-4ba73c66d20d"
          },
          {
            "name": "YTD 2023",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR startyear =",
              "    STARTOFYEAR(Calendario[Data])-365",
              "VAR enddate =",
              "    LASTDATE(fConsolidado_Faturamento[DataFaturamento])-365",
              "RETURN",
              "    CALCULATE (",
              "        SUM (fConsolidado_Faturamento[FAT LIQUIDO]),",
              "        DATESBETWEEN (Calendario[Data], startyear, enddate)",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "107e291d-3dcb-4be6-887a-035fc4cf5734"
          },
          {
            "name": "24vs23",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "",
              "VAR  Divisao = DIVIDE([FatR$],[YTD 2023])-1",
              "RETURN",
              "IF(Divisao = -1, BLANK(), Divisao)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "04adfbe2-2773-4067-ab83-844b32567fc8"
          },
          {
            "name": "YTG",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "([FatR$]/6)*6*(1+'Parâmetro'[Valor Parâmetro])",
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "4b50dd37-32d6-41b2-b0fb-c2089928a001"
          },
          {
            "name": "MEDIA YTG",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "([YTG]/6)*(1+'Parâmetro'[Valor Parâmetro])",
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "2d4857a7-cfdc-44b5-84f2-52c608bb59cc"
          },
          {
            "name": "FY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "[YTG]+[FatR$]",
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "322bb771-5822-4ddd-93c6-57131229b087"
          },
          {
            "name": "FYvs2023",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "",
              "VAR  Divisao = DIVIDE([FY],[Fat 2023])-1",
              "RETURN",
              "IF(Divisao = -1, BLANK(), Divisao)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "4ea7b72e-587a-49ad-8977-f664d50eef3a"
          },
          {
            "name": "GAPYTG",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "[FY]-[FatR$]",
            "formatString": "\"R$\"\\ #,0;-\"R$\"\\ #,0;\"R$\"\\ #,0",
            "lineageTag": "8a5a6ad3-ca98-41e0-b181-494cb35162c5"
          },
          {
            "name": "FYT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "[YTGT]+[Qt Ton]",
            "lineageTag": "b5a377ec-463c-437b-a827-ed41ea73dc4c"
          },
          {
            "name": "Faturamento YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE([FatR$],",
              "                    DATESYTD(Calendario[Data]))"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "e6d0fc93-e80f-4c9c-8bf1-845c3b9e78dd"
          },
          {
            "name": "24vs23.2",
            "expression": [
              "",
              "",
              "VAR  Divisao = DIVIDE([Faturamento YTD],[YTD 2023])-1",
              "RETURN",
              "IF(Divisao = -1, BLANK(), Divisao)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ec7acc80-97a7-426a-a055-7fd7632beac4"
          },
          {
            "name": "YoY-YTD",
            "expression": [
              "",
              "VAR varENTRADA = [YTD 2023]",
              "VAR varResultado = ",
              "DIVIDE(",
              "    [Faturamento YTD]- varENTRADA, varENTRADA)",
              "VAR varFormato = FORMAT(varResultado, \"#%\")",
              "    RETURN",
              "    IF(varResultado = BLANK(), \"🟢\"&varFormato, IF(varResultado > 0, \"🟢\"&varFormato, \"🔴\"&varFormato))"
            ],
            "lineageTag": "0a2df016-91ea-47fe-b583-82a38c443f07"
          }
        ],
        "partitions": [
          {
            "name": "Medidas_YTG",
            "mode": "import",
            "queryGroup": "Medidas",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Coluna 1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Parâmetro",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b50b559162194a53859f1d764efcd4fd"
          }
        ],
        "columns": [
          {
            "name": "Parâmetro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "double",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isNameInferred": false,
            "lineageTag": "fc2d59b0-334b-432f-9148-aca7951ca7d3",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "2c715f21-3cf1-4392-b9dd-8153f054c210",
        "measures": [
          {
            "name": "Valor Parâmetro",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SELECTEDVALUE('Parâmetro'[Parâmetro])",
            "lineageTag": "85ac3183-d129-4ace-8bb2-a3b7d69b55be"
          }
        ],
        "partitions": [
          {
            "name": "Parâmetro",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(0.01,3, 0.01)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Medidas_Ton",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "1cc3563d-5875-4fbb-ac61-aa6677dd1281",
        "measures": [
          {
            "name": "Qt Ton",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR varTON = SUM(fConsolidado_Faturamento[Peso])",
              "RETURN",
              "varTON/1000"
            ],
            "formatString": "#,0",
            "lineageTag": "6dcd32e2-d1bd-46d0-b2ca-1f61df3bda9d"
          },
          {
            "name": "Ton2022",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "CALCULATE([Qt Ton], Calendario[Ano] = \"2022\")",
            "formatString": "#,0",
            "lineageTag": "f80f8fb2-f8e9-437b-89af-60d77d7f02c9"
          },
          {
            "name": "Ton2023",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "CALCULATE([Qt Ton], Calendario[Ano] = \"2023\")",
            "formatString": "#,0",
            "lineageTag": "3d038365-3156-42c7-b85f-7e76281760d6"
          },
          {
            "name": "YTD 2023T",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "VAR startyear =",
              "    STARTOFYEAR(Calendario[Data])-365",
              "VAR enddate =",
              "    LASTDATE(fConsolidado_Faturamento[DataFaturamento])-365",
              "RETURN",
              "    CALCULATE (",
              "        SUM (fConsolidado_Faturamento[Peso])/1000,",
              "        DATESBETWEEN (Calendario[Data], startyear, enddate))"
            ],
            "formatString": "#,0",
            "lineageTag": "fb2f55d2-769f-40a4-94cb-7ac37abfa7e9"
          },
          {
            "name": "23vs22T",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "",
              "VAR  Divisao = DIVIDE([Ton2023],[Ton2022])-1",
              "RETURN",
              "IF(Divisao = -1, BLANK(), Divisao)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "00d9a3d6-8ad9-4937-a87e-520560e74333"
          },
          {
            "name": "24vs23T",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "",
              "VAR  Divisao = DIVIDE([Qt Ton],[YTD 2023T])-1",
              "RETURN",
              "IF(Divisao = -1, BLANK(), Divisao)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "5a154433-6ce1-483d-8a08-ef09764f83cb"
          },
          {
            "name": "YTGT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "([Qt Ton]/5)*7*(1+'Parâmetro'[Valor Parâmetro])",
            "formatString": "#,0",
            "lineageTag": "4cd30989-c9ba-47b6-9e8e-13fcca805bcd"
          },
          {
            "name": "MEDIA YTGT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "([YTGT]/7)*(1+'Parâmetro'[Valor Parâmetro])",
            "formatString": "#,0",
            "lineageTag": "d24d5b59-10d7-480f-b98c-8ff223335660"
          },
          {
            "name": "FYvs2023T",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "",
              "",
              "VAR  Divisao = DIVIDE([FYT],[Ton2023])-1",
              "RETURN",
              "IF(Divisao = -1, BLANK(), Divisao)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f248c08b-df67-4395-a893-b4c70b5f51eb"
          },
          {
            "name": "GAPYTGT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "[FYT]-[Qt Ton]",
            "formatString": "#,0",
            "lineageTag": "6dfba884-f118-43d9-bd19-fbdde50b9f29"
          },
          {
            "name": "M-1ton",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "[Qt Ton],",
              "    DATEADD(Calendario[Data],",
              "    -1,",
              "    MONTH",
              "    ))"
            ],
            "formatString": "#,0",
            "lineageTag": "f7a691ae-8855-4a64-ba1c-5eb5157fa98f"
          },
          {
            "name": "M-LYton",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "[Qt Ton],",
              "    DATEADD(Calendario[Data],",
              "    -1,",
              "    YEAR",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "cf75c9ec-e31e-4fea-a8b5-d31d14dc425a"
          },
          {
            "name": "Meta Ton",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "CALCULATE(SUM(Meta[Valor]), Meta[TipoMeta] = \"TONS\")",
            "formatString": "#,0",
            "lineageTag": "2ebcf921-9d28-4bf5-a508-51395167c9a2"
          },
          {
            "name": "% Aderencia.ton",
            "expression": "DIVIDE([Qt Ton], [Meta Ton])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "81686515-fed9-4492-8157-f776fae6c65e"
          },
          {
            "name": "% M-1ton",
            "expression": [
              "",
              "",
              "VAR  Divisao = DIVIDE([Qt Ton],[M-1ton])-1",
              "RETURN",
              "IF(Divisao = -1, BLANK(), Divisao)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "cff76adc-b0b2-4c16-b173-da160cab570f"
          },
          {
            "name": "% M-LYton",
            "expression": [
              "",
              "VAR  Divisao = DIVIDE([Qt Ton],[M-LYton])-1",
              "RETURN",
              "IF(Divisao = -1, BLANK(), Divisao)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "d052f5a8-b546-4327-a908-b9249f95be15"
          },
          {
            "name": "Fat D-1ton",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "VAR vDataContexto = CALCULATE(TODAY())",
              "VAR vUltimaDataFato = CALCULATE(",
              "    MAX(fConsolidado_Faturamento[DataFaturamento]), ",
              "    Calendario[Data] < vDataContexto)",
              "",
              "    VAR vValorUltimaData =",
              "    CALCULATE(",
              "        [Qt Ton],",
              "        Calendario[Data] = vUltimaDataFato",
              "    )",
              "    RETURN",
              "    vValorUltimaData"
            ],
            "formatString": "0",
            "lineageTag": "3ba028f4-faa9-4ff1-9860-2e4175b1ff23"
          },
          {
            "name": "ENTRADA D-1 TON",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "VAR vDataContexto = CALCULATE(TODAY())",
              "VAR vUltimaDataFato = CALCULATE(",
              "    MAX(fMonitorPedido[DataImplant]), ",
              "    Calendario[Data] < vDataContexto)",
              "",
              "    VAR vValorUltimaData =",
              "    CALCULATE(",
              "        [Cart Ton],",
              "        Calendario[Data] = vUltimaDataFato",
              "    )",
              "    RETURN",
              "    vValorUltimaData"
            ],
            "formatString": "#,0",
            "lineageTag": "38e99855-1c8f-4754-a16b-28a87b2c8529"
          },
          {
            "name": "TON Cancelado",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "VAR varCancelado = [Qt Cancelada]*SUM(dProduto[PesoKG])/1000",
              "RETURN",
              "IF(varCancelado = BLANK(), 0, varCancelado)"
            ],
            "formatString": "#,0",
            "lineageTag": "58c4374a-94c5-4beb-b615-c6b598e1c357"
          },
          {
            "name": "DEV Ton",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(SUM(fConsolidado_Faturamento[QtdDevolvida]) * SUM(dProduto[PesoKG])/1000)*-1"
            ],
            "formatString": "#,0",
            "lineageTag": "53187c24-46db-4b21-b2d3-9a7188d5c540"
          }
        ],
        "partitions": [
          {
            "name": "Medidas_Ton",
            "mode": "import",
            "queryGroup": "Medidas",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Coluna 1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dEstabelecimento",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Estabelecimentoid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eb6d7bc6-8ab6-4aaa-9340-0bc83d0d58ab",
            "sourceColumn": "Estabelecimentoid",
            "summarizeBy": "none"
          },
          {
            "name": "CODIGO",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7cf643ca-f60b-427b-a7fc-77f0453b4350",
            "sourceColumn": "CODIGO",
            "summarizeBy": "sum"
          },
          {
            "name": "Origemid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5bfb2bb4-8b3e-4446-b560-419e3ea13998",
            "sourceColumn": "Origemid",
            "summarizeBy": "none"
          },
          {
            "name": "Nome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a3faab9-d4a8-4100-92be-aa145d1ce5e0",
            "sourceColumn": "Nome",
            "summarizeBy": "none"
          },
          {
            "name": "Estabeleciemnto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "23ea4b79-04ed-4686-af94-dd2150d9d9ff",
            "sourceColumn": "Estabeleciemnto",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e111398e-b9bf-4a23-9451-2ce7adbd45ad",
        "partitions": [
          {
            "name": "dEstabelecimento",
            "mode": "import",
            "queryGroup": "Bases Manuais",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(#\"Servidor (2)\", #\"Banco (2)\"),",
                "    bi_view_EmpresaSubempresa = Fonte{[Schema=\"bi\",Item=\"view_estabelecimento\"]}[Data]",
                "in",
                "    bi_view_EmpresaSubempresa"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "RLS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "71b62faa-68ac-4455-a7d7-e727bc375e37",
            "sourceColumn": "email",
            "summarizeBy": "none"
          },
          {
            "name": "Vendedorid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "76959d41-44a8-4030-8964-139b3dd9b26b",
            "sourceColumn": "Vendedorid",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "50c2fa51-b60b-443f-8935-729efc425a0b",
        "partitions": [
          {
            "name": "RLS",
            "mode": "import",
            "queryGroup": "Bases Manuais",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(Servidor, Banco),",
                "    bi_view_Produto = Fonte{[Schema=\"dbo\",Item=\"view_rls_estruturaComercial\"]}[Data]",
                "in",
                "    bi_view_Produto"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Parâmetro 2",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "6096a60fbcf44467beaed74dd7936f55"
          }
        ],
        "columns": [
          {
            "name": "Parâmetro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "2c4358ae-f3d8-4a9e-8f06-0dc38fee08a0",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parâmetro Campos"
                }
              ]
            },
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Campos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "dc605f4e-f3ed-4ecf-9a15-4e327382e7d6",
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "62fc4b4b-da60-4bfa-adab-a37333912e80",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "a6f20890-cbc9-4578-b3ec-aa7b78244564",
        "partitions": [
          {
            "name": "Parâmetro 2",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"ENTRADA CART. TOTAL\", NAMEOF('Medidas_Cart'[Entrada Carteira]), 0),",
                "    (\"CARTEIRA ABERTA\", NAMEOF('Medidas_Cart'[Total Aberto]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Parâmetro 3",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ff536f53c7d14555b53c4ec59b34e7a8"
          }
        ],
        "columns": [
          {
            "name": "Parâmetro",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "31356ea1-a96b-49e8-af8f-047dc66e3624",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parâmetro Campos"
                }
              ]
            },
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Campos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "237933ee-948b-48c3-ae4e-8707481ad63b",
            "sortByColumn": "Parâmetro Pedido",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parâmetro Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "b15e00aa-8b7e-4cab-86dc-298132a13944",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "387797d3-27ce-4424-a7fb-346fb58ff965",
        "partitions": [
          {
            "name": "Parâmetro 3",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"STATUS CARTEIRA\", NAMEOF('fMonitorPedido'[Sit Carteira 2]), 0),",
                "    (\"COD ROTA\", NAMEOF('dClientes'[CodigoRota]), 1),",
                "    (\"REGIONAL\", NAMEOF('dVendedores'[regional]), 2),",
                "    (\"COD ESTABELECIMENTO\", NAMEOF('dEstabelecimento'[Estabeleciemnto]), 3)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Estrategico Coord_Vend",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "perfil",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "abd80928-e34b-4840-9b23-e2f2947612c3",
            "sourceColumn": "perfil",
            "summarizeBy": "none"
          },
          {
            "name": "Caracteristicaestrategico",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d57f46ec-c118-4330-8ad0-53e6a2eaa967",
            "sourceColumn": "Caracteristicaestrategico",
            "summarizeBy": "none"
          },
          {
            "name": "chave",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f66c4013-65dc-4695-b850-684ffc253d25",
            "sourceColumn": "chave",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cae82556-f6d9-444f-a839-8a45464db388",
        "partitions": [
          {
            "name": "Estrategico Coord_Vend",
            "mode": "import",
            "queryGroup": "Bases Manuais",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(Servidor, Banco),",
                "    bi_view_Produto = Fonte{[Schema=\"bi\",Item=\"view_ProdutoPerfilEstrategico\"]}[Data],",
                "    #\"Duplicatas Removidas\" = Table.Distinct(bi_view_Produto, {\"chave\"})",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Data Atualização",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Data Atualização",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "d9ee4fb5-384e-4701-a6bc-24da5dad56fc",
            "sourceColumn": "Data Atualização",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6fad8bec-4ba5-416f-9f6a-104e0877b800",
        "partitions": [
          {
            "name": "Data Atualização",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = DateTime.LocalNow(),",
                "    #\"Convertido para Tabela\" = #table(1, {{Fonte}}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Convertido para Tabela\",{{\"Column1\", type date}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Tipo Alterado\",{{\"Column1\", \"Data Atualização\"}})",
                "in",
                "    #\"Colunas Renomeadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dFaixa",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "COORD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7af6a7cb-986c-4f9e-9162-316c48c9b544",
            "sourceColumn": "COORD",
            "summarizeBy": "sum"
          },
          {
            "name": "FAIXA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "411a8120-fc93-4fe5-a4b4-2f10c74163e2",
            "sourceColumn": "FAIXA",
            "summarizeBy": "none"
          },
          {
            "name": "%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5d41303e-4c1f-4f13-acdb-15588c4c9e91",
            "sourceColumn": "%",
            "summarizeBy": "sum"
          },
          {
            "name": "%GER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "446a811b-1095-4773-b133-cc9ec7c006dd",
            "sourceColumn": "%GER",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "4f376277-f054-4ffc-8780-c06c6b83c3bd",
        "partitions": [
          {
            "name": "dFaixa",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"fZIxDoMwDEWvUkViYzBObMjIUqk3qIS4/zVKUgr+VpoFRXrm+cfxtgWRRGEMz/X1Xh/TcYppKF8ewj46zAUsFc8NHI9TkoJTPHF2claQZy8nkGcn//a+5CILJhdMbnCVZ0xucCO5KHXliskTo1y7YxHJKJ9c8ozJndzgKieQ6+ySLyC3mK+/L7nFjeSqMz4oJre4yBm3xeJ4DfUnn4kVk7OVA+ZTe8sBx1N7y5nIjaXem0aiRsE9mD8FpYG4Asna33btb7v2t12nhtx0twXcuCAU3A3Ogv0D\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [COORD = _t, FAIXA = _t, #\"%\" = _t, #\"%GER\" = _t]),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(Fonte,{{\"%\", Percentage.Type}, {\"%GER\", Percentage.Type}}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Tipo Alterado1\",{{\"COORD\", Int64.Type}, {\"FAIXA\", type text}, {\"%\", Percentage.Type}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Faixa",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "VendedorId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "072cb3ea-2d22-420d-8b30-f98bf309cbda",
            "sourceColumn": "VendedorId",
            "summarizeBy": "none"
          },
          {
            "name": "CodigoCoordenador",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cf150b82-78ef-4754-937f-ac5f190b7729",
            "sourceColumn": "CodigoCoordenador",
            "summarizeBy": "sum"
          },
          {
            "name": "FAIXA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7fc1ac0f-17cf-4e83-9394-d8457ce59a4b",
            "sourceColumn": "FAIXA",
            "summarizeBy": "none"
          },
          {
            "name": "%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9f630971-9f8a-4259-8785-f485cf572bb9",
            "sourceColumn": "%",
            "summarizeBy": "sum"
          },
          {
            "name": "Codigo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8f9f916d-3754-4b22-9642-59f679a1081b",
            "sourceColumn": "Codigo",
            "summarizeBy": "sum"
          },
          {
            "name": "VOLUME COORD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "176e395d-79e1-4aad-996e-63efe750797d",
            "sourceColumn": "VOLUME COORD",
            "summarizeBy": "sum"
          },
          {
            "name": "VOLUME GER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4b57ba43-9502-4856-b232-70386b6160ea",
            "sourceColumn": "VOLUME GER",
            "summarizeBy": "sum"
          },
          {
            "name": "%GER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "184b162d-b78b-4d08-8068-d2645a577f54",
            "sourceColumn": "%GER",
            "summarizeBy": "sum"
          },
          {
            "name": "FAIXA.1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdcc45d7-ceb8-4393-b89a-78affe8e7bdf",
            "sourceColumn": "FAIXA.1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0a7f347f-81ab-48be-a542-7ba5e1d20310",
        "measures": [
          {
            "name": "Faix1",
            "expression": [
              "",
              "VAR varmedia = AVERAGE(Faixa[%])",
              "RETURN",
              "IF(varmedia = BLANK(), 0, varmedia)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a4d9cf03-8740-4250-a4cf-ef952ccc4d25"
          },
          {
            "name": "Faixvol",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR varmedia = AVERAGE(Faixa[VOLUME COORD])",
              "RETURN",
              "IF(varmedia = BLANK(), 0, varmedia)"
            ],
            "lineageTag": "9ba658bd-698d-4fae-894d-7b1b20f654ff"
          },
          {
            "name": "Faix2",
            "expression": [
              "",
              "VAR varmedia = AVERAGE(Faixa[%GER])",
              "RETURN",
              "IF(varmedia = BLANK(), 0, varmedia)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d7ede38c-7ce7-4970-ab27-9c60524b0f0f"
          }
        ],
        "partitions": [
          {
            "name": "Faixa",
            "mode": "import",
            "queryGroup": "Bases Manuais",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(Servidor, Banco),",
                "    bi_view_PessoaVendedor = Fonte{[Schema=\"bi\",Item=\"view_vendedor\"]}[Data],",
                "    #\"Outras Colunas Removidas\" = Table.SelectColumns(bi_view_PessoaVendedor,{\"VendedorId\", \"Codigo\", \"CodigoCoordenador\"}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Outras Colunas Removidas\",{{\"CodigoCoordenador\", Int64.Type}}),",
                "    #\"Consultas Mescladas\" = Table.NestedJoin(#\"Tipo Alterado\", {\"CodigoCoordenador\"}, dFaixa, {\"COORD\"}, \"dFaixa\", JoinKind.LeftOuter),",
                "    #\"dFaixa Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas\", \"dFaixa\", {\"FAIXA\", \"%\", \"%GER\"}, {\"FAIXA\", \"%\", \"%GER\"}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"dFaixa Expandido\", each true),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Linhas Filtradas\",{{\"Codigo\", Int64.Type}}),",
                "    #\"Consultas Mescladas1\" = Table.NestedJoin(#\"Tipo Alterado1\", {\"Codigo\"}, #\"Faixa Volume\", {\"VENDEDOR\"}, \"Faixa Volume\", JoinKind.LeftOuter),",
                "    #\"Faixa Volume Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas1\", \"Faixa Volume\", {\"FAIXA\", \"VOLUME COORD\", \"VOLUME GER\"}, {\"FAIXA.1\", \"VOLUME COORD\", \"VOLUME GER\"})",
                "in",
                "    #\"Faixa Volume Expandido\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Medidas CurvasABC",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "lineageTag": "312c7507-9a0f-4d74-b73a-88fa67f92ef8",
        "measures": [
          {
            "name": "FatAcumulado",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR varFatContexto = [FatR$]",
              "VAR varFatTotal = CALCULATE([FatR$], ALL(dProduto))",
              "VAR varFatAcumulado = ",
              "CALCULATE(",
              "    [FatR$], ",
              "    FILTER(",
              "        ALL(dProduto), ",
              "        [FatR$] >= varFatContexto",
              "    )",
              ")",
              "RETURN",
              "varFatAcumulado",
              ""
            ],
            "lineageTag": "157d6169-2af7-45f1-89f8-bda137351a60"
          },
          {
            "name": "Pareto Produto",
            "expression": [
              "",
              "VAR varFatTravado = CALCULATE([FatR$], ALL(dProduto))",
              "RETURN",
              "DIVIDE([FatAcumulado], varFatTravado)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "442f5524-c6b9-46c5-a06f-b7b09b21f596"
          },
          {
            "name": "ClasseABC",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    [Pareto Produto] >= 1, \"D\",",
              "    [Pareto Produto] >= 0.95, \"C\",",
              "    [Pareto Produto] >= 0.80, \"B\",",
              "    \"A\")"
            ],
            "lineageTag": "abdd5d85-5d45-4b75-8725-353f9bcddbb0"
          },
          {
            "name": "FiltraABC",
            "expression": [
              "",
              "IF(SELECTEDVALUE(AuxiliarABC[ABC]) = [ClasseABC], 1,0)"
            ],
            "formatString": "0",
            "lineageTag": "ee6253c2-6b0d-44f8-b202-91c1b26dace3"
          },
          {
            "name": "FATURAMENTO TOTAL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE([FatR$], ",
              "FILTER(",
              "    dProduto,",
              "    [Pareto Produto] <= MAX(AuxiliarABC[LimiSup]) &&",
              "    [Pareto Produto] > MIN(AuxiliarABC[LimInf])",
              ")",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "4edeafc4-6ee0-404f-8768-a1d4008d905b"
          },
          {
            "name": "Ranking R$",
            "expression": "RANKX(ALL(dProduto), [FatR$])",
            "formatString": "0",
            "lineageTag": "da382526-9d69-480b-963c-81f90f717d67"
          },
          {
            "name": "Ranking R$ LY",
            "expression": "CALCULATE([Ranking R$], SAMEPERIODLASTYEAR(Calendario[Data]))",
            "formatString": "0",
            "lineageTag": "fa4c8a26-ff27-49bb-87fb-fe1ab0e19bdc"
          },
          {
            "name": "CLASSE A",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE('Medidas CurvasABC'[FATURAMENTO TOTAL], AuxiliarABC[ABC] = \"A\")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "79cc64f5-d0ff-4473-9f96-d6c775188cbd"
          },
          {
            "name": "CLASSE B",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE('Medidas CurvasABC'[FATURAMENTO TOTAL], AuxiliarABC[ABC] = \"B\")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "aec683e5-8349-4271-9db9-3bc531c75138"
          },
          {
            "name": "CLASSE C",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": [
              "",
              "CALCULATE('Medidas CurvasABC'[FATURAMENTO TOTAL], AuxiliarABC[ABC] = \"C\")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "b27fb608-131c-499f-93d8-5cf19f7fb97a"
          },
          {
            "name": "80%",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "0.8",
            "lineageTag": "a5b4ce46-50a8-4c4d-b1b8-109c9c2fdbac"
          },
          {
            "name": "DIF RANK",
            "expression": [
              "",
              "IF( [Ranking R$] = [Ranking R$ LY], 1, IF([Ranking R$]<= [Ranking R$ LY], 2, IF([Ranking R$] > [Ranking R$ LY], 0,0)))"
            ],
            "formatString": "0",
            "lineageTag": "4d174646-e64c-4ebe-aaa2-43e221935955"
          },
          {
            "name": "QT SKU'S A",
            "expression": [
              "",
              "CALCULATE(DISTINCTCOUNT(dProduto[Denominacao]), FILTER(dProduto,[ClasseABC] = \"A\"), ALL(Calendario[Data]))"
            ],
            "formatString": "0",
            "lineageTag": "9a304484-d33e-40c1-b1d7-257e86f60169"
          },
          {
            "name": "QT SKU'S B",
            "expression": [
              "",
              "CALCULATE(DISTINCTCOUNT(dProduto[Denominacao]), FILTER(dProduto,[ClasseABC] = \"B\"), ALL(Calendario[Data]))"
            ],
            "formatString": "0",
            "lineageTag": "b8ab108c-83e5-4535-b592-be5acd3b4aea"
          },
          {
            "name": "QT SKU'S C",
            "expression": [
              "",
              "CALCULATE(DISTINCTCOUNT(dProduto[Denominacao]), FILTER(dProduto,[ClasseABC] = \"C\"), ALL(Calendario[Data]))"
            ],
            "formatString": "0",
            "lineageTag": "b4f8da74-c1ba-48dd-ad6b-40424f12575f"
          },
          {
            "name": "QT TOTAL SKU'S",
            "expression": [
              "",
              "[QT SKU'S A]+[QT SKU'S B]+[QT SKU'S C]"
            ],
            "formatString": "0",
            "lineageTag": "2bf0db85-0bc3-43f5-b7e4-fd96e42a481a"
          },
          {
            "name": "% Represen",
            "expression": [
              "",
              "DIVIDE([FATURAMENTO TOTAL], [Fattravado])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "fc85a8c4-aae5-45ed-bbe4-b6a8348c7969"
          },
          {
            "name": "Fattravado",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE([FatR$], ALL(dProduto))"
            ],
            "lineageTag": "909f6f6a-3012-4297-81d4-ee516e594aa5"
          },
          {
            "name": "SubT A",
            "expression": [
              "",
              "[QT SKU'S A]  &  \" Sku's representam \" & FORMAT([Rep A], \"#.#0%\") & \" do faturamento total. \" "
            ],
            "lineageTag": "a608534c-0ea0-41fa-8167-265596cecc5d"
          },
          {
            "name": "Rep A",
            "expression": [
              "",
              "CALCULATE([% Represen], AuxiliarABC[ABC] = \"A\")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "831ed572-08ec-491a-a9e1-b82170aecfc1"
          },
          {
            "name": "Rep B",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE([% Represen], AuxiliarABC[ABC] = \"B\")"
            ],
            "lineageTag": "5e49d3b9-b433-45cb-a224-d50fe4d7facf"
          },
          {
            "name": "SubT B",
            "expression": [
              "",
              "[QT SKU'S B]  &  \" Sku's representam \" & FORMAT([Rep B], \"#.#0%\") & \" do faturamento total. \""
            ],
            "lineageTag": "b006ed28-de34-455c-99a4-43c678d157ed"
          },
          {
            "name": "Rep C",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE([% Represen], AuxiliarABC[ABC] = \"C\")"
            ],
            "lineageTag": "056100ad-fa45-4390-9cd6-a8ac4918db6d"
          },
          {
            "name": "SubT C",
            "expression": [
              "",
              "[QT SKU'S C]  &  \" Sku's representam \" & FORMAT([Rep C], \"#.#0%\") & \" do faturamento total. \""
            ],
            "lineageTag": "f33a2354-a726-4218-8cbf-d65276e81b11"
          },
          {
            "name": "Pareto ly",
            "expression": [
              "",
              "CALCULATE([Pareto Produto], SAMEPERIODLASTYEAR(Calendario[Data]))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6fef5e09-ba3e-4553-a44c-b924936994e4"
          },
          {
            "name": "Pareto Cliente",
            "expression": [
              "",
              "VAR varFatTravado = CALCULATE([FatR$], ALL(dClientes))",
              "RETURN",
              "DIVIDE([FatAcumulado], varFatTravado)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4d1e1ae3-d34a-493f-849f-6358337ef1b4"
          }
        ],
        "partitions": [
          {
            "name": "Medidas CurvasABC",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Coluna 1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "AuxiliarABC",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "columns": [
          {
            "name": "ABC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6614f29-4c7f-4d16-b7e2-8863de60e3e2",
            "sourceColumn": "ABC",
            "summarizeBy": "none"
          },
          {
            "name": "LimInf",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "72a14754-8cd1-4b95-abcd-2b1a2ea40f15",
            "sourceColumn": "LimInf",
            "summarizeBy": "sum"
          },
          {
            "name": "LimiSup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "de891982-aafa-4db4-85b4-2d3b66f432e4",
            "sourceColumn": "LimiSup",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "1bc15fd9-5713-4382-8d98-8bee99a2e489",
        "measures": [
          {
            "name": "Medida",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "lineageTag": "bcc82590-495a-4a18-9e75-bb44a6962dfb"
          }
        ],
        "partitions": [
          {
            "name": "AuxiliarABC",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WclTSUTIAYR0LA6VYnWglJwgHTFqagoWcYRwdJUOwgAuYpaNkohQbCwA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ABC = _t, LimInf = _t, LimiSup = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"ABC\", type text}, {\"LimInf\", Percentage.Type}, {\"LimiSup\", Percentage.Type}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Estrategico_Gerencia",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProdutoId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "41976b6f-720b-4bb0-a090-7d80c159a748",
            "sourceColumn": "ProdutoId",
            "summarizeBy": "count"
          },
          {
            "name": "Regional",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3a6965f-65d3-40eb-9509-818640202481",
            "sourceColumn": "Regional",
            "summarizeBy": "none"
          },
          {
            "name": "Categoria",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86f5f9d9-ee7f-4d36-8661-63abc1ff9b2e",
            "sourceColumn": "Categoria",
            "summarizeBy": "none"
          },
          {
            "name": "dVendedores.VendedorId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ca80fdc3-9026-44d8-8a0c-c2e093609e57",
            "sourceColumn": "dVendedores.VendedorId",
            "summarizeBy": "none"
          },
          {
            "name": "Chave",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3ada608-5f05-4fa7-b301-694b86029883",
            "sourceColumn": "Chave",
            "summarizeBy": "none"
          },
          {
            "name": "Chave 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "995c5198-1a14-4ed6-969c-10f39ca8da42",
            "sourceColumn": "Chave 2",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ab5c49e7-70d1-45f0-93ac-9f0df652c983",
        "partitions": [
          {
            "name": "Estrategico_Gerencia",
            "mode": "import",
            "queryGroup": "Bases Manuais",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(Servidor, Banco),",
                "    bi_view_Produto = Fonte{[Schema=\"bi\",Item=\"view_Produto\"]}[Data],",
                "    #\"Valor Substituído\" = Table.ReplaceValue(bi_view_Produto,\"PÓ BTV LAVANDA 5KG\",\"PÓ BTV 5KG\",Replacer.ReplaceText,{\"SubCategoria1\"}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Valor Substituído\",{{\"Codigo\", Int64.Type}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"CATEGORIA EST SUDESTE\", \"REGIONAL CE - MA\", \"VAREJO PE\", \"VAREJO AL\", \"VAREJO PB\", \"VAREJO CE\", \"VAREJO RN\", \"Denominacao\", \"PesoKG\", \"Marca\", \"CATEGORIA GERAL\", \"SubCategoria1\", \"CatPcp\", \"Categoria2\", \"ESTRATEGICO MACRO\", \"CATTÁTICOS\", \"Status\", \"Fabrica\", \"Codigo\", \"PLT\"}),",
                "    #\"Colunas Não Dinâmicas\" = Table.UnpivotOtherColumns(#\"Colunas Removidas\", {\"ProdutoId\"}, \"Atributo\", \"Valor\"),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Colunas Não Dinâmicas\",{{\"Valor\", \"Categoria\"}, {\"Atributo\", \"Regional\"}}),",
                "    #\"Valor Substituído1\" = Table.ReplaceValue(#\"Colunas Renomeadas\",\"CATEGORIA EST MULTI\",\"GERENCIA MULTICANAL\",Replacer.ReplaceText,{\"Regional\"}),",
                "    #\"Valor Substituído2\" = Table.ReplaceValue(#\"Valor Substituído1\",\"CATEGORIA EST VAREJO\",\"GERENCIA VAREJO\",Replacer.ReplaceText,{\"Regional\"}),",
                "    #\"Valor Substituído3\" = Table.ReplaceValue(#\"Valor Substituído2\",\"REGIONAL CE - CE\",\"REGIONAL CE\",Replacer.ReplaceText,{\"Regional\"}),",
                "    #\"Consultas Mescladas\" = Table.NestedJoin(#\"Valor Substituído3\", {\"Regional\"}, dVendedores, {\"regional\"}, \"dVendedores\", JoinKind.LeftOuter),",
                "    #\"dVendedores Expandido\" = Table.ExpandTableColumn(#\"Consultas Mescladas\", \"dVendedores\", {\"VendedorId\"}, {\"dVendedores.VendedorId\"}),",
                "    #\"Coluna Mesclada Inserida\" = Table.AddColumn(#\"dVendedores Expandido\", \"Chave\", each Text.Combine({Text.From([dVendedores.VendedorId], \"pt-BR\"), Text.From([ProdutoId], \"pt-BR\")}, \"|\"), type text),",
                "    #\"Coluna Mesclada Inserida1\" = Table.AddColumn(#\"Coluna Mesclada Inserida\", \"Chave 2\", each Text.Combine({Text.From([dVendedores.VendedorId], \"pt-BR\"), [Regional]}, \"|\"), type text),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Coluna Mesclada Inserida1\", {\"Chave\"})",
                "in",
                "    #\"Duplicatas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Faixa Volume",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "VENDEDOR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d849c9c6-54e5-490e-b79b-6d8098a7c08b",
            "sourceColumn": "VENDEDOR",
            "summarizeBy": "sum"
          },
          {
            "name": "FAIXA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb59c2d5-5e93-4664-b27e-760ac60bc12b",
            "sourceColumn": "FAIXA",
            "summarizeBy": "none"
          },
          {
            "name": "VOLUME COORD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1ec2b278-59e9-4dfb-bebd-09c615ed7abd",
            "sourceColumn": "VOLUME COORD",
            "summarizeBy": "sum"
          },
          {
            "name": "VOLUME GER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "34b59c7d-dd98-4573-a064-60fa72e9707e",
            "sourceColumn": "VOLUME GER",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "b6d986e1-93d9-4455-bfbf-448c30f36eaf",
        "partitions": [
          {
            "name": "Faixa Volume",
            "mode": "import",
            "queryGroup": "Bases Manuais",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"fVpJjhxHDPyKMWcdipksZuVRFwP+gQFB//+Gq1vGdJCsiMM0BBFM7kHG9Pz69XXa\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [VENDEDOR = _t, FAIXA = _t, #\"VOLUME COORD\" = _t, #\"VOLUME GER\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"VENDEDOR\", Int64.Type}, {\"FAIXA\", type text}, {\"VOLUME COORD\", Int64.Type}, {\"VOLUME GER\", Int64.Type}}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Tipo Alterado\", each true)",
                "in",
                "    #\"Linhas Filtradas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Grupo de cálculo",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "item de cálculo",
              "expression": "SELECTEDMEASURE()"
            }
          ]
        },
        "columns": [
          {
            "name": "Coluna do grupo de cálculo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eef16a5e-c9ad-4e74-8e6d-012c1029b3b9",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a2e96bf2-442a-4dd2-8a36-301d4a2885ca",
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "61286a96-1857-4153-9866-fd43d0e7ad03",
        "partitions": [
          {
            "name": "Grupo de cálculo",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "teste campo",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "2fb0585869074ce7a2ea0de2471aac2e"
          }
        ],
        "columns": [
          {
            "name": "teste campo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "8a7b2c2e-6bec-4375-8181-af5201798319",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "teste campo Campos"
                }
              ]
            },
            "sortByColumn": "teste campo Pedido",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "teste campo Campos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "7dfd29b5-ddee-4fee-96e8-0797c34b6857",
            "sortByColumn": "teste campo Pedido",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "teste campo Pedido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "e33fd275-57a3-423b-85d5-50c724f123c1",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "29fd9e4d-8874-4d88-9cd7-7ebbffcb0f9f",
        "partitions": [
          {
            "name": "teste campo",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"FatR$\", NAMEOF('Medidas_Fat'[FatR$]), 0),",
                "    (\"LY\", NAMEOF('Medidas_Fat'[LY]), 1),",
                "    (\"Qt Fat\", NAMEOF('Medidas_Fat'[Qt Fat]), 2),",
                "    (\"Qt M-LY\", NAMEOF('Medidas_Fat'[Qt M-LY]), 3)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Medidas_Lanç",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          }
        ],
        "lineageTag": "1a3d094a-f814-4b20-b2b2-0d7c31b9503b",
        "measures": [
          {
            "name": "Qt Pedids Acumu.",
            "expression": [
              "",
              "",
              "CALCULATE([Qt Pedidos], ",
              "      FILTER(",
              "        ALL(Calendario[Data]),",
              "        Calendario[Data] < MIN(Calendario[Data])))"
            ],
            "formatString": "0",
            "lineageTag": "11b4cc90-9ec4-4458-a905-6ca63b91051f"
          },
          {
            "name": "Qt Clientes",
            "expression": [
              "",
              "DISTINCTCOUNT(fConsolidado_Faturamento[emitenteID])"
            ],
            "formatString": "0",
            "lineageTag": "c13ddf0f-f1c4-4958-aded-f9ad015db77b"
          },
          {
            "name": "Qt Clientes Novos",
            "expression": [
              "",
              "",
              "VAR _Contexto = VALUES(fConsolidado_Faturamento[emitenteID])",
              "VAR _DataContexto = MIN(Calendario[Data])",
              "VAR _Anteriores = ",
              "    CALCULATETABLE(VALUES(fConsolidado_Faturamento[emitenteID]),",
              "    Calendario[Data] < _DataContexto",
              "    )",
              "",
              "VAR _Fonte = EXCEPT(_Contexto, _Anteriores)",
              "RETURN",
              "COUNTROWS(_Fonte)"
            ],
            "formatString": "0",
            "lineageTag": "1a8abc7b-339e-4929-8a96-d28f0ae60361"
          },
          {
            "name": "Qt Clientes Recorrentes",
            "expression": [
              "",
              "[Qt Clientes]- [Qt Clientes Novos]"
            ],
            "formatString": "0",
            "lineageTag": "dd37ddd2-b0f6-4180-8f18-ea03cf0dc6f2"
          },
          {
            "name": "Teste recompra",
            "expression": [
              "",
              "",
              "VAR DataContexto = CALCULATE([Qt Fat], ",
              "      FILTER(",
              "    Calendario,",
              "        Calendario[Data] <= MAX(Calendario[Data])))",
              "",
              "     VAR _Trimestre =    ",
              "     CALCULATE([Qt Fat], ",
              "           DATESINPERIOD(Calendario[Data], ",
              "           EOMONTH(TODAY(), -1), -1, QUARTER))",
              "",
              "           VAR _FatTotal = CALCULATE([Qt Fat], ALL(Calendario))",
              "",
              "RETURN",
              "IF(DataContexto > 0, 1, ",
              "                      ",
              "       IF( DataContexto = 0 && _Trimestre >= 1, 2, ",
              "                                                              ",
              "                IF(DataContexto = 0 && _Trimestre = 0 && _FatTotal >= 1, 3, ",
              "                                                                             IF(_FatTotal = 0, 0))))"
            ],
            "formatString": "0",
            "lineageTag": "126db467-958c-4d5b-975d-124cdb406b73"
          },
          {
            "name": "DataContexto",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE([Qt Fat], ",
              "      FILTER(",
              "    Calendario,",
              "        Calendario[Data] <= MAX(Calendario[Data])))",
              ""
            ],
            "lineageTag": "29fdd0e1-7d70-41d2-9d05-3cd9329e4dac"
          }
        ],
        "partitions": [
          {
            "name": "Medidas_Lanç",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Coluna 1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dVend_Auxi",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "VendedorId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "61d988e6-4818-4c13-bbb4-894b68383651",
            "sourceColumn": "VendedorId",
            "summarizeBy": "none"
          },
          {
            "name": "Nome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f7ba58c7-adc9-4e18-8404-f6df1ddbd075",
            "sourceColumn": "Nome",
            "summarizeBy": "none"
          },
          {
            "name": "Codigo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "687073ac-cbe7-4f4d-9cde-190d29120c36",
            "sourceColumn": "Codigo",
            "summarizeBy": "sum"
          },
          {
            "name": "regional",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "788cd1ea-5108-46e9-8620-84e2fff5d107",
            "sourceColumn": "regional",
            "summarizeBy": "none"
          },
          {
            "name": "STATUS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "30f57a1d-b5ff-4bba-9292-8579d0e78f87",
            "sourceColumn": "STATUS",
            "summarizeBy": "none"
          },
          {
            "name": "NomeGerente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c9722b1-2fe5-4847-aff9-9601d0c8e7d4",
            "sourceColumn": "NomeGerente",
            "summarizeBy": "none"
          },
          {
            "name": "CodigoGerente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a137997a-1bad-4790-8667-175c561c303e",
            "sourceColumn": "CodigoGerente",
            "summarizeBy": "sum"
          },
          {
            "name": "NomeCoordenador",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ba480b9-db6c-45cb-9e3b-430bd048344d",
            "sourceColumn": "NomeCoordenador",
            "summarizeBy": "none"
          },
          {
            "name": "CodigoCoordenador",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0daaa0c1-4870-410c-abba-21b5efd0bc75",
            "sourceColumn": "CodigoCoordenador",
            "summarizeBy": "sum"
          },
          {
            "name": "perfil",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f75cdd6-9cd5-4a64-b6b1-25ada4afc98e",
            "sourceColumn": "perfil",
            "summarizeBy": "none"
          },
          {
            "name": "Chave2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "00150239-fa76-4142-849f-5acdae65e330",
            "sourceColumn": "Chave2",
            "summarizeBy": "none"
          },
          {
            "name": "PerfilRmv",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b792a41-5b24-4bfe-883f-34d831e1585e",
            "sourceColumn": "PerfilRmv",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f5d161f0-cde0-4dc5-8c11-c4b342347c08",
        "partitions": [
          {
            "name": "dVend_Auxi",
            "mode": "import",
            "queryGroup": "Bases Manuais",
            "source": {
              "expression": [
                "let",
                "    Fonte = Sql.Database(Servidor, Banco),",
                "    bi_view_PessoaVendedor = Fonte{[Schema=\"bi\",Item=\"view_vendedor\"]}[Data],",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(bi_view_PessoaVendedor,{{\"Codigo\", Int64.Type}, {\"CodigoGerente\", Int64.Type}, {\"CodigoCoordenador\", Int64.Type}}),",
                "    #\"Coluna Mesclada Inserida\" = Table.AddColumn(#\"Tipo Alterado\", \"Chave2\", each Text.Combine({Text.From([VendedorId], \"pt-BR\"), [regional]}, \"|\"), type text),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Coluna Mesclada Inserida\",null,\"OUTROS\",Replacer.ReplaceValue,{\"regional\"})",
                "in",
                "    #\"Valor Substituído\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}